package com.algo.advent;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

class NumberMatcher {
    static class Node {
        private final Map<Character, Node> next;
        private int number;

        public Node(int number) {
            this.number = number;
            this.next = new HashMap<>();
        }

        public Map<Character, Node> getNext() {
            return next;
        }

        public int getNumber() {
            return number;
        }

        public void setNumber(int number) {
            this.number = number;
        }
    }

    private final Node start;

    public NumberMatcher() {
        this.start = new Node(-1);
    }

    void add(String number, int value) {
        char[] chars = number.toCharArray();
        addChars(value, chars);
        char[] charsReversed = new StringBuffer(number).reverse().toString().toCharArray();
        addChars(value, charsReversed);
    }

    private void addChars(int value, char[] chars) {
        Node current = start;
        for (int idx = 0; idx < chars.length; idx++) {
            Map<Character, Node> next = current.getNext();
            current = next.computeIfAbsent(chars[idx], __ -> new Node(-1));
        }
        current.setNumber(value);
    }

    private Node getStartOrNew(char curr) {
        Node node = start.getNext().get(curr);
        if (node == null) {
            return new Node(-1);
        }
        return node;
    }

    static NumberMatcher getInstance() {
        NumberMatcher matcher = new NumberMatcher();
        matcher.add("one", 1);
        matcher.add("two", 2);
        matcher.add("three", 3);
        matcher.add("four", 4);
        matcher.add("five", 5);
        matcher.add("six", 6);
        matcher.add("seven", 7);
        matcher.add("eight", 8);
        matcher.add("nine", 9);
        return matcher;
    }

    List<Node> currents = new LinkedList<>();

    int walk(char value) {
        List<Node> neighbours = new LinkedList<>();
        currents.add(start);
        for (Node current : currents) {
            Node next = current.getNext().get(value);
            if (next != null) {
                neighbours.add(next);
            }
        }
        currents = neighbours;
        for (Node next : neighbours) {
            if (next.number != -1) {
                return next.number;
            }
        }
        return -1;
    }
}

public class DayOne {

    public static void main(String[] args) {
        String first = "1abc2\n" +
                "pqr3stu8vwx\n" +
                "a1b2c3d4e5f\n" +
                "treb7uchet";

        String input = "9sixsevenz3\n" +
                "seven1cvdvnhpgthfhfljmnq\n" +
                "6tvxlgrsevenjvbxbfqrsk4seven\n" +
                "9zml\n" +
                "52sevenone\n" +
                "41onevfsgvssxnpsix38four\n" +
                "15ninedzhkpfstrscggbqhktwo\n" +
                "rxbfsvhpnjvsixmxfhhmvdvg26rgrfj43\n" +
                "gcbq2sghsv4fiveeightrlhchsfs2hsrjknfz\n" +
                "tworgqpdjzrzf7one\n" +
                "fivefive18\n" +
                "sixfztrcxmbzktwofour3fiveeight\n" +
                "2g4stjrjjmbngvljfvg24\n" +
                "5jkcdxkltwo71\n" +
                "vhpttjh2\n" +
                "3threegmsppjrngfive7\n" +
                "ktkgsvkthreevone2xxrxzgdqpnone2xnf\n" +
                "llxzczt3seventwotwosix5\n" +
                "eighteighthvllljmgg82eightseven2\n" +
                "9hcjzphpktwo76xfpdvnhklzthreejrzkdknhrktwo\n" +
                "fourtwojrvzzctzs5eight2vlm\n" +
                "zoneightthree2hvhfsprqxmlsix7onevn4\n" +
                "56sixssevenfour5twonine\n" +
                "58fourfour\n" +
                "683\n" +
                "8fourninenhfpz9eightptsnnb\n" +
                "gddmrzlpn9\n" +
                "g3qsbqmbhqqp1eightkjggcxpmzgg\n" +
                "6bzjqs7nxpvgtwoseven\n" +
                "271lonepxp2flbmbz\n" +
                "5sgshnrfn9qxt8xsnhtdtx6\n" +
                "cnhflx4sevensixonethree\n" +
                "595six93\n" +
                "6eight8jbtmxdqpj96mqkrdxt9tpbpppl\n" +
                "68qvmgth371lqcrglmvqxtwonfk\n" +
                "mbqbhpmhspsbbxgflg98zn\n" +
                "8oneqzvdcrh\n" +
                "kb6\n" +
                "mhgvpmfgjfourfourtwo4\n" +
                "81mvcgqxlktbpkkrsgbdgeightbqn65\n" +
                "hlbhthree1seven9\n" +
                "vqczmtvqsnd3sh63\n" +
                "qrzngvmk8\n" +
                "chpldqtkhqbvdvmnqd5\n" +
                "6three6two\n" +
                "sevensix4tjvkcfgpone98\n" +
                "96zgpcq9four\n" +
                "cbvksjgvvklhnksixfive7kmmxg\n" +
                "threeljfr1vzskggfvjsccc\n" +
                "8pfourthreetwosix\n" +
                "l2sbdcvngvmtzrtq\n" +
                "hjdxfj94\n" +
                "2hbhfbjfteightnr5sixfpfjkn\n" +
                "2sevenjqlpprggjlkddqv9oneightpj\n" +
                "fivebfmkdrrrdkclkscqmtwo6five7\n" +
                "fourrp8fnbp9d1fl7\n" +
                "six8pffqfpjl2nine\n" +
                "91sdjlghq5\n" +
                "fivemrmcnjmfcnck2\n" +
                "v1\n" +
                "78htfvqsztlsixeight\n" +
                "5zpjtbgpkvkxbgpsp3cgklflkhdteightwortv\n" +
                "mcxqfgxt49sevenone9\n" +
                "rt2dsvpf\n" +
                "9dzxmfour76six\n" +
                "tsbmbdrgmzsjeightonezqhqb5qn\n" +
                "seven8zllmz\n" +
                "373onefourthree\n" +
                "1fourfivezthdcxfr\n" +
                "996seven2four\n" +
                "8smnghninezczdlzxxgf\n" +
                "7cbqfzrmhxdmrdr94tz\n" +
                "6vstr65tfivelmhjshhj\n" +
                "248fourlckvrtnzz4sxdqpgkvh\n" +
                "zfivejfgfgdhfrhr6\n" +
                "one2tworsmtnzfjhvvqjnp\n" +
                "5threefourjsnfzninethreejrknzfn\n" +
                "seven9nine\n" +
                "gthree15fivemzpnqgttcq1\n" +
                "fivevvvkgtvs3four4\n" +
                "five121three\n" +
                "7fourn\n" +
                "sixdnineqvfqglmn98516\n" +
                "ninesixrppx4\n" +
                "threesevenxbskhlqbone276\n" +
                "fivesixfour82\n" +
                "tmdnvgrkjxfour9\n" +
                "61nine\n" +
                "vtxpkcgb48jzx8rgeight7\n" +
                "twoonetwo3\n" +
                "four167bnbdtxq4xvdgckkpb2\n" +
                "xgbxvx7ninehmvqlldtxls88qhztfldr4\n" +
                "5qxsfdchthree41\n" +
                "fournb5gfqzfrlnc5fivethree1\n" +
                "t6fourh3\n" +
                "ninefgzksevenseven5sbcpnczgflqptjhk\n" +
                "6three4\n" +
                "5tnplthreeeightvsk2fivesix9\n" +
                "three8hcvnmvbhbtwo\n" +
                "6jnfourdbcgzgfzczbc\n" +
                "z53\n" +
                "fourxzhgjfrrbmkcheightfive7seven8oneightb\n" +
                "2fivehkhnbtm\n" +
                "rptgktsnzvsslcvfsevensixfive72\n" +
                "95chcvtxv4\n" +
                "ninenldnphcpn93fivetwo7\n" +
                "threeeight675vmhvgtxxc2bp\n" +
                "hfdmpv6\n" +
                "xpffsljjcm27\n" +
                "8sevensix8\n" +
                "7hmszcvzpf9eightqqxgjdnhpfour68\n" +
                "2czrnzdpxsjsdldcxq2vzgfrthsssix\n" +
                "four5bdxdnvtgcbdzzsxjdlbckninetwo5\n" +
                "35fourfive6\n" +
                "z5eight3r84hvptgskcclbsgh\n" +
                "2eightljldmconeeightgvhm\n" +
                "4sixsixsixfourthree\n" +
                "tnnthreelfmhone1onepfivevdg\n" +
                "8nine9lmpptxstrrbqbjrjtm4seven\n" +
                "2ltqd9mnrbhcsprz\n" +
                "two5ptcjzbqnk2spvlcxqvglndgvrlm5fiveeight\n" +
                "52sqstnqpdeight55\n" +
                "2nvskvthreeqhkqvjzqrk1\n" +
                "gbkqz127four\n" +
                "8zmngr5381rb\n" +
                "klrlqvkhslvbxdtwofour4cmlpbdm6\n" +
                "eightninenjnmc8zrnrltgfmfour\n" +
                "38sv7\n" +
                "eightvtkkmhhninebmgdvconenine7sixjkdzxcr\n" +
                "h14bdgvknbnjq4fv\n" +
                "74svtwo\n" +
                "7three5sixone4\n" +
                "zseightwo6five\n" +
                "shkznseven5ninefivefour8\n" +
                "mcmztmrgctqszzpqs8tworfvkseven\n" +
                "onejjmdfour15nine4\n" +
                "7bxqxxxvlthree4tb9five\n" +
                "twoqzpx6hj\n" +
                "68hbdjdd45two\n" +
                "68\n" +
                "4hxlfbgvtdmbhnpfzxpnltfivemtmczjcbffour4\n" +
                "fourseven4hfffmtqoneglgnnsrqsmbnxr\n" +
                "dhbbmcxtv7five9ffjjcmshv31seven\n" +
                "foursbgvhgbggnine6three4zznzcvmxxqktpdhff\n" +
                "681cvdh\n" +
                "3ninefivefive\n" +
                "jg4dnnxzdtwoqdbvfsix\n" +
                "g4dbeight6rkc\n" +
                "236bjcppxmlnine\n" +
                "5crthreefive8\n" +
                "6twoknqfbmeight5c\n" +
                "64eightrkvvtjtsonefour9eightwoqxq\n" +
                "sm7sixfivexbrkvhtl9\n" +
                "threeninetwotwo1one\n" +
                "tjjeightwoj3gsdmdseventwo1\n" +
                "63sevenk4blssxzkcq29ztjlnx\n" +
                "ckpleightxgngnhkj2threem\n" +
                "8knckxzrfbbpxldzninennnmkxkzzstsflv9two\n" +
                "rmldrlcvccgdbvdnxvqr3ninefznpqrrtd1cfpjrvjzs\n" +
                "5twojdflbxnlslnsjtklqkrbklvkthreejgxkfzeight\n" +
                "sevenxfpzvss6\n" +
                "one61\n" +
                "2seven7eight\n" +
                "fivefive5fourtwo9vjmxmtpv\n" +
                "4pxfour\n" +
                "twofive1eight9ldjbfbzhhffdb\n" +
                "onefive7four93pjchnkrzvz\n" +
                "4194hgfslhdczj1ztjtnccpjseven8\n" +
                "sixtkjmtcthreezjfcgbdhvqlmbpzmc7\n" +
                "nineeightvnd55sftvbf4sevenrkgbjskxbj\n" +
                "kqoneighttpqcnsphsfour7eight9sixthree\n" +
                "5foursvfsztnfivekkkftdfbptmrgcone\n" +
                "sevensix8one5zjlfcrqzvp\n" +
                "1hmvpbhzcbgbgvdkblnhgklltxx\n" +
                "55xszsjgbd2fk\n" +
                "hdrhmddj6ninebcfhbd\n" +
                "f91six\n" +
                "3tltgktntqpkeighthbqhlxcqnffgbfvxrkmr2\n" +
                "3jthree\n" +
                "2eightplclghthree\n" +
                "771\n" +
                "5gccqqmzmx81twob\n" +
                "6pgnqbsqglk44mvslnxghckcbtffxvkq2\n" +
                "twooneone5\n" +
                "twohbxsxj2six826hlkdjnnz\n" +
                "17tbdmntksvn89fivethreeseven\n" +
                "sixplznhmbgzmlh3six1\n" +
                "h2kvpbnkcxrssevenfive\n" +
                "jhpmnksix7fgnbhgv8fztxfrpfvmnrvhzr\n" +
                "vskpbnine3vjqdlmv9\n" +
                "vmg86ht36sbnzphxfive\n" +
                "klqxeightnine6\n" +
                "4nfninelzshl26\n" +
                "zqsb243hfdtvgx\n" +
                "two9tzcrmrsix81xsgvldl\n" +
                "ggqeightwo5bdpqtjkgzdclxsqptwo1eight1\n" +
                "pvfzftdxqzfourmmbzlbzcfsevenfivesix5\n" +
                "fivelt5fivegshvshpvkpqlddmfj6\n" +
                "cjpzgsvgsz7kzcpr1sixfour\n" +
                "8two4onesevenseven7v\n" +
                "ztwonefouronezdvggfive8eightzflpvlnxfspgrtwo\n" +
                "one7tphmqvfltwo\n" +
                "49seven2three\n" +
                "9rntqtxseveneightgflqzkrxhglrnvrvz1\n" +
                "four6nine7\n" +
                "5nine3\n" +
                "4ddpkhft12hrhjvbtdxthree1tpknk\n" +
                "7k\n" +
                "fmlrpkxqktzdldrs84onefptgdjspldljvnine8\n" +
                "oneseven4nineqbqlbxf2kqnpr\n" +
                "ffivetwo97mp\n" +
                "47h92ffcd6\n" +
                "two7tcjvxdvctfivepcqxjnzfourfcndmdmnjseven\n" +
                "cjdjxmnmpqr6cqvcscdpg\n" +
                "onefour95\n" +
                "seven9onenine\n" +
                "trpvv6six64kfmxqrdvbsevenhqzk9\n" +
                "tsgpcfxsgsgmhd7rvfz\n" +
                "66788\n" +
                "five26b\n" +
                "chcbxone1\n" +
                "6mrlfkqjssdxbtzkshvc8hjltjjxthkl\n" +
                "four5sdsevenvztqmzkm21threenine\n" +
                "snxrlctcztlbntnxkpmbs2\n" +
                "652nnhvz6vcgx\n" +
                "2zrxljdgsnnfour5fourp4\n" +
                "85lzkjln55239\n" +
                "51fourrnbkb4\n" +
                "xbvsjmgsjdvhjpxdjhl1\n" +
                "6sevencfhtbm4svgpzeight8three4\n" +
                "827cclvxpdgqlhrjvrgxbxthree\n" +
                "8pgqr\n" +
                "three2ninesjztqjdhdv\n" +
                "538one59one\n" +
                "6lcmxone4ninehzzb13\n" +
                "phckzkgtxdcnine8onefour744\n" +
                "five61\n" +
                "skbknb9qknrlszdt\n" +
                "fivenine6jnxfsseven7\n" +
                "lfj2onethree4198\n" +
                "bb9\n" +
                "kfljcb5zssbrlzml\n" +
                "twohmspvflmxnine2eight8\n" +
                "4onegfnxxqpqnfour7\n" +
                "qvg7seven4\n" +
                "85bheightghccknine1three\n" +
                "fivedpthreeseven1fiveseven2\n" +
                "6nine3gzlbtvtvlnine6eightmdn\n" +
                "seven3seven58gzmdjmchdrzxgkgbbfrf4\n" +
                "2lxbnnsixgdcv6hrqjnfhdmz\n" +
                "8threefiveflbfmthreegtvckvpxkd856\n" +
                "jbnkkbvfivexqzm238zxvztfl\n" +
                "68kglf7\n" +
                "9fivetzjsixkvfrngxbfbbjpd69\n" +
                "ninejgz82fivenltntmfs6xpxc\n" +
                "fourlseight3qrrrrddzlone\n" +
                "seventwoqfkj2qxzddcgtb348\n" +
                "xgjddt5\n" +
                "q8bfhspkgmsevenninevdqmlzxznhmdlg\n" +
                "qc2sqqlkfrkj652xpgzjskr3four\n" +
                "two3tpl1cvmldrrghr\n" +
                "qhoneoneseven9zfivevrkkjhtdf\n" +
                "ddjczzpcvkksjzdcmxkhmbds2\n" +
                "qnvgskzdb3nine77sdvfhfqsnv2kjffgsvz\n" +
                "six8three3vbpnkb\n" +
                "rgjmvgtgfour36qqbqznkjv78cbpdqb\n" +
                "fournshtzbqfourthreefive8hsbpflngrvzdhone\n" +
                "toneightone9four\n" +
                "fourkkxtzpfivetwovnvxmtkeight4t9\n" +
                "tbxlvkc5vgcmdckzv\n" +
                "7threethree\n" +
                "9ntqnzpldshfqlc2six\n" +
                "8zs7five\n" +
                "3threethreentqthree\n" +
                "jmxjl4four5\n" +
                "jnmrhzpdvbvvg9qcxjjmv2msrszndl\n" +
                "onezjrkeight4two2seven\n" +
                "32jlkhszgnkklbrsgpplphh\n" +
                "1gsdqlbgt5eight1\n" +
                "219\n" +
                "93gcgx2twothree9xggt\n" +
                "5fivenine1fiveplgmlffsvzbtqpb\n" +
                "qv7lthszlgxeightnine\n" +
                "7sevenmhmkcrkkq\n" +
                "mxmmgqp4rptkbhfourvjh\n" +
                "3mrmhgjmdv6pvfkbmconelmlckqkxjfiveznxg\n" +
                "7one1kbjnmtpskgsix99\n" +
                "bsvjlfgrcvvhmnfjzktdeight9914\n" +
                "csfrjtwofivebcrcmggfpfsevenlmhncfb1two\n" +
                "3five1vphfournine1kvfvzrtm\n" +
                "nineeight3vxrdvttwo\n" +
                "snncrseventwo5sevencjgl\n" +
                "ngmgxnlsjjhvqpcxjshninesix63\n" +
                "4threeone2twotzsseven4prqdrnjln\n" +
                "fivegfmn391\n" +
                "three5xflqlnrjgfpzt5\n" +
                "28two\n" +
                "six729twoeight7\n" +
                "eight11\n" +
                "sevenseven1fqcsevenonekrgxmone\n" +
                "8rvlj62\n" +
                "one3ninethree\n" +
                "89s6two2twofive\n" +
                "pnhhshxqb312\n" +
                "vlnj5eight9\n" +
                "5seven5eights3eight1\n" +
                "6kqvkbjrfveighttwo6\n" +
                "5twofour\n" +
                "ztnkthreefive1fivetwovqjpx3three\n" +
                "qs2\n" +
                "2vft3\n" +
                "zjr1zjpxndcsc\n" +
                "76threesix\n" +
                "1four88n7\n" +
                "9mrrkjzlxdc\n" +
                "1ll89\n" +
                "fgvcseven81\n" +
                "4789vtvtcseven\n" +
                "2lcfbmqcqt\n" +
                "5sixonefive\n" +
                "cdoneight1onetwo96lpllgksff4hrzjkxng\n" +
                "gntghdtwo1\n" +
                "eightninefpdttgflvr2\n" +
                "8zcnfm4krxhfive67seven6\n" +
                "2hxpgvxgsmc\n" +
                "trlvltteighteightrzkxntpdtpl24\n" +
                "hkttzcmnck7s1seven\n" +
                "sevensnmhgdxpbksngnflnthreemlqgdvphzk5tvmzjvdzbcseven\n" +
                "eightpsbcshqcbppkgfxcnrgtwoeightfour6four\n" +
                "53xktsrztnxninehpjjjktqnsixfivefive7\n" +
                "sevenonebkdseven1seven\n" +
                "11sixzdqbbppninehhkpxdbmlv2chddf\n" +
                "3one3fivesevenlljjmxvzbcnqtszvzspsevenb\n" +
                "1txlrnsb1vq28kpvv\n" +
                "1two855\n" +
                "2lxzhcjl1qfslvldkpdcxf\n" +
                "9seven3fcqtzfive\n" +
                "eight4phtznrb69xqbmxmdvxnsstnine\n" +
                "eightfive2sixnhxcffkq95\n" +
                "five28cppfive1two6\n" +
                "p8\n" +
                "kn8\n" +
                "6hvzkkr4nine2seventwo4\n" +
                "39134\n" +
                "dztwone3kqlbbbknfive\n" +
                "xvvdhddonekcgqqqzgxhlg2seven\n" +
                "237rhppmlcmhsevenvnjxhzfnzbzrsdl\n" +
                "1kgq1qsphhpcdeightjnfsdggnlnckgfbj2\n" +
                "bnvpzxtnt16two\n" +
                "mkhvcrfqdtwo3qfmhs\n" +
                "1hkjncflcz5four7bbgpgcmnv94seven\n" +
                "7seventmmhfgngfxt4\n" +
                "98238\n" +
                "3zmnhxqjqhjtptwoqtptmxfdp3seven\n" +
                "bkqxlrtf4\n" +
                "onefive8tvb6fiveone6\n" +
                "1four3seventhree5mvsbsdjz\n" +
                "jtjsjflv5gxvhdgvrbgbdcjjtchkvmf\n" +
                "sixthreefcrbqzqs7psczkdc\n" +
                "dc572twonejgl\n" +
                "2xkrpz9dfslbjvmbdkgsixhkgcvdgktq\n" +
                "five114\n" +
                "8two85\n" +
                "9fbh79mqbfsxcnn1two6\n" +
                "6one9fivetwo\n" +
                "gsjljnkhhvqlmmvcthreemfcbnjsbkvzzsnkb7\n" +
                "nine49twojdqjsfbzsixrhbjhn4\n" +
                "3threesix1\n" +
                "52six1twoseven\n" +
                "eight9dbb6hhjnt\n" +
                "gsnqmninefivefbqcrlneight1\n" +
                "jxczccqqpxbcq8\n" +
                "1ckvkgqtvqrpvdrfivejjhhfkxvvhfm\n" +
                "sixdxgvgglfh4qzczn8jpgqmgbzkmcdjfnhmh9\n" +
                "eight7nine9\n" +
                "tzqv6fivefourhfz\n" +
                "sixnine2vkmdnkgtgnbbkcxvvsc2bf22\n" +
                "78two41\n" +
                "srpeightwovrhmbnkpnsix1\n" +
                "fourninemfcvlstbmflzqf9lgvlvrlff2srxpzvrp2\n" +
                "kcgtwone9eight\n" +
                "7three1onesix1m3\n" +
                "rgk2fiveeightthreegckdbd9dml\n" +
                "sevencx9onenineeight6\n" +
                "9ninetwocb4thttbkqj\n" +
                "five26vrc2krtfivejpgdmtjg\n" +
                "2ninethree7cnxbkpvthreefiveqclhc\n" +
                "98seven28\n" +
                "onetwosevensix9three8\n" +
                "sevensix2\n" +
                "ninesixlrdgpbrzs7onedrtlqpfour1\n" +
                "pmvxzronexxxvbdrjr7\n" +
                "15eight\n" +
                "crksmfive64\n" +
                "onetwo6fivemqkddjfxndjfpzmeight5xzk\n" +
                "gq3ninetwo9\n" +
                "8mgkvbpmbzpd7\n" +
                "xfbvzlbpvb79\n" +
                "kkbrvppqcg5\n" +
                "94dkngltfzs98\n" +
                "rchmjsrh7onejcknbl\n" +
                "9threesixxrbzjt\n" +
                "3963seven48sixeight\n" +
                "98992\n" +
                "7zqd\n" +
                "sevenseven814htznfour1\n" +
                "ninefivedfrtwoone5\n" +
                "qzgrrng8six\n" +
                "3742zsgbqgfvzlgsgfmxql86eight\n" +
                "seven7zdfrhonemfhcfmclxj25three\n" +
                "8pnhpnsqxh\n" +
                "62seven\n" +
                "eightpfgmmdg945ksctbstnh6cdxvgqbl\n" +
                "932zsnvmcone1ktfqfmbnsfive\n" +
                "dglzhqjthreemzpm78\n" +
                "one7sk13ghnmvsrprg\n" +
                "jdvzccvczspscxj5rzzdqdd44txvprhqx\n" +
                "sevengmtcflgvpzonecvmbtgknine7kngpspbg\n" +
                "xmqk6jmhmdtvh2kbchmsgpjrv2four\n" +
                "tntsjnine3jksrrvone\n" +
                "xfzgbzfive3ninekmnjrlqkzq96foursix\n" +
                "3xbcth723\n" +
                "zbvtsrxh94s\n" +
                "threesix8mjchcpvmdgfive17xb\n" +
                "8eightnbbzhfhf4fiveeightmnzqldztsnfour\n" +
                "tkglxsb6one62rhzggrtgqxqnvjzfmb\n" +
                "gtj2onempqp34qfjnlxtztvjvsv\n" +
                "2eightzxdgc3\n" +
                "32dgskjkh2\n" +
                "sevendnvrcm5166\n" +
                "5knxkkjh5\n" +
                "fssjcvvckqjrcghcmlrkcvxl22\n" +
                "2jbhdlfjtbfivetkjbjmtrgxrdmxsix\n" +
                "fivedm8pzjfngzfsk35\n" +
                "two31ldnvx\n" +
                "5mfive9ggkq\n" +
                "vqdhfsfkrpp44trqpnkqsdxvvdxc\n" +
                "lkdqckshmn1rgrvtjqj\n" +
                "ttwoneqzmsxzskbbnkfh8onespphhmsix31\n" +
                "jknbnfvbf1snjscz5\n" +
                "sevenvjn9\n" +
                "ninetjzhbdjsffthreecfctlsfrz2\n" +
                "6ninedqmxfqxssbhrrffpdhjvhqtkxfour9\n" +
                "6tlrxcvhtllkrhjxqt3two3\n" +
                "eighteightfive79\n" +
                "5sixfive7bjlkninefour\n" +
                "xrgrxsvm5bhcmzggbkrljnssxgpgdlv2four8\n" +
                "1mxlnrtsjgdlcsncktrsfour\n" +
                "8xtkgjjbtjfnc62vsshkjp\n" +
                "91twoninetwo\n" +
                "ninefour5nbnnzhtfiveggrjf7zqzblbml\n" +
                "sixfour42rtbvlpcnv4\n" +
                "oneczchdtwoglj9279\n" +
                "jfvv5rdkpzldsxh\n" +
                "ninexghzhdqk67\n" +
                "gnllbntksevenseven7sixeightvgnfd\n" +
                "qzqjxcqrs8fivesevenrnvnq9nqnchpjpmfkgtjqcsvtv\n" +
                "6sixsixspzppcstlhqlssvt\n" +
                "4hhfndc17rjrrzvbjj\n" +
                "xm6sevenseven2fivendnn\n" +
                "threesixd6nrxmxgcbjfrtlmpkjnoneshmrn\n" +
                "ncnpmsixfour4two\n" +
                "pqvz9fourkkmfvzbjqbfour\n" +
                "szspfourhsqkfkfcndcnineone5khdb\n" +
                "six29sixlkfbphnrzcjl\n" +
                "cdtwonenine73\n" +
                "mtlqpjcqcseven29\n" +
                "8onekdvdmjbmbjtdngxhjjchdv7bvsbjqszlhvht\n" +
                "fivevqnjsvnhvnine1kxcsjmzx\n" +
                "6six32twonine\n" +
                "nnsix5fcsrdvoneightcn\n" +
                "11rzzpnrtnsevenmvnhgrsgngthree\n" +
                "3fourjfonefoursevenbbfour\n" +
                "fiveclfour7seventwoeight\n" +
                "4zvzlfive7hkzhbqrleight8\n" +
                "4eightthreemthreeq\n" +
                "66nine\n" +
                "dlnm59eight\n" +
                "fourthreexvgpp7\n" +
                "85sixfnrjqvmzmtbpxttrn\n" +
                "one2seven\n" +
                "63fourztwofdssrbjbcvhltg7\n" +
                "fdstgbg1qdznxnvftfvfnr6djj\n" +
                "5dcmbkrlvsrfvbdfqfour\n" +
                "xp6fourrcfxdnktdctwofour\n" +
                "9three4threeone6\n" +
                "8pjzglttwofive9\n" +
                "2gsix9sixthree\n" +
                "ptwofive3t\n" +
                "4hqkqzjkqddnnhxkrfnhgbkthreethree2\n" +
                "threedthcktqkcthree22\n" +
                "2gdlntwoseven527tzxbzkdjbv\n" +
                "6hbxrgxzcnlbnz6\n" +
                "ds7mvjbvfkn\n" +
                "sixrpd7eightfour6\n" +
                "qfoursspgghsflcrvqeight6\n" +
                "94hxsj5\n" +
                "bhhhnfnnkninexnjtjxrphrkc9mdmjp\n" +
                "pbttrcplcsrldftsgk4991threepcbhxxfrgjddpz\n" +
                "6four1fgjmjcnj3nbxxnnxhjhv\n" +
                "6onefourshbzqgxjnhpmz\n" +
                "9onedvscbrdj5\n" +
                "jgjrpgcjztvkqseven8sznzl16dzrhmhnq7\n" +
                "ctlbzmcctmkzpqtsdztbmllqnoneoneonenine28\n" +
                "znkkbdsix23msxkcs\n" +
                "seventwo365one2nlmlbgh1\n" +
                "mtzthdjtonezfsixms5mxjpftkd\n" +
                "onenine8ksxnslf16njqldnnkjx\n" +
                "pzjl78nztcgnj211zxnmhxzrjjh\n" +
                "twozkf3fiveshpt\n" +
                "seventwo387bnfsix\n" +
                "2xvvtzthreexjfxxg4seven\n" +
                "8vgjxlvjc4twoglhmpgtsbfonethreeqbpcfbmz\n" +
                "mhlgjlbm68rmeightnineone\n" +
                "threezhldnzscqfour9seventfkj\n" +
                "cnprmbrprlhmonesixlksvgzseventhreehdzh2\n" +
                "smp215344two\n" +
                "5nineonefive8sevenzvlfrprdq\n" +
                "rvf583\n" +
                "four8nine4crzpff\n" +
                "rhnsqgnncnjzhpx297qmj18\n" +
                "oneqlx716452\n" +
                "mg3zptnqbm\n" +
                "4ssgqpsevenznzlnnsbjpxkfvlkrjckxrhqsevenzrgjlkcffb\n" +
                "six9fourshjkhspkcffiveeightqqkvktvjsmmnfrthree\n" +
                "sixdljbtwoninetwo6ninesevenn\n" +
                "kcjqfvldclrmsd52qn\n" +
                "352one\n" +
                "7nine7\n" +
                "9fourjcveighth\n" +
                "5twoz73\n" +
                "bbsvvbjc1one5gtts3nine\n" +
                "four2six\n" +
                "7nine5\n" +
                "nxjfthslhc2sspz\n" +
                "69onethreefour8nq4eightwoqh\n" +
                "8mfpmmthree6eightbksq7\n" +
                "98bzjlfjm\n" +
                "six541threepklngxmfthreevvkdgxpfour\n" +
                "seventhree4ninesix\n" +
                "7ninejkcxsixsixlvffhbkjkfive2rdnd\n" +
                "9flxnpfddx68mfgnkkdqlonenblbszdvvbfour\n" +
                "threemfk22vf\n" +
                "threeninemh6\n" +
                "88six\n" +
                "4eightrtthree\n" +
                "4rkjjgppc2lkvnhbnhffnrvqsj8\n" +
                "65gdpxxz\n" +
                "5fourfour6\n" +
                "six9m9eightfour\n" +
                "21szgzbcg\n" +
                "krzfvtsgp3\n" +
                "six2threethreebskteight4twoeight\n" +
                "58bjrnzbqg\n" +
                "8eight4four3\n" +
                "four6qcrnthree2\n" +
                "j8nine7gqlvtqxlzdtcbonetwo\n" +
                "sixvlthree55seven37\n" +
                "48sevengfgzczbg82\n" +
                "eightsix2qsqfgmsrscfive\n" +
                "zpbxnxbnmjthreebmksffpkd7seight8nine\n" +
                "vfvhcvnsevenkbnhxxhhc3csk79\n" +
                "147threesixtwo\n" +
                "hldlvjninehnqxd7fiveeight7sixkkbmjxnjf\n" +
                "six3gjbkbpgzdszl3f\n" +
                "donethree3seven7xvfgnthree\n" +
                "3lgpzhzmfftwoeightjhlngfn6five57\n" +
                "5fnfl6vkncfsrrrsmxsl\n" +
                "7ss\n" +
                "five6gsncdxsixnhphl85\n" +
                "3rklhfbkhfour884\n" +
                "xsjseven7\n" +
                "58mxlmsevennine7cssix\n" +
                "1jnbbfourv\n" +
                "r21kstwo\n" +
                "zrqlghpcsixeightseventlnpnxpzv3\n" +
                "887\n" +
                "zeightwo3xzjvmqxpjtbvj\n" +
                "1brtqrcvbrrqsqbpsl1sevenseven22\n" +
                "4qcddseven\n" +
                "mg3xxlgdkblgg1htdjtfthpv\n" +
                "9eightwoslp\n" +
                "ggqvtwonsfsevenfour73ccmzkz1\n" +
                "7rfjfqh9nine\n" +
                "gnpnrzzkdtfcseven45hvv\n" +
                "34one1\n" +
                "xzkfl9fivebxhcxrmfzszonekgzcvk1six\n" +
                "8pzscngsixsrtjqqlk25ldczspzfdxrzhh\n" +
                "zktjxcb72twosix\n" +
                "9mvtk5jqhtwo\n" +
                "two82klbfdf\n" +
                "xstrdlsmx2onesevenrmgpjlrtfsfourfive4\n" +
                "four1djgssbq8sixfive\n" +
                "j1jkgzrjmnfxonejsvgzznsevenprbqbjn\n" +
                "two65ffglkhgqb8xdxmldhtllj3\n" +
                "lqqqsrjf27four9dgpjcgz\n" +
                "fptvlnfzpfm99eight8five5xtgqt\n" +
                "sgrdlpplhb2six6\n" +
                "one4811eightrvkbchcngmone\n" +
                "bcsv46dgxglfxsrn9two\n" +
                "spshpxtwo6c\n" +
                "1sevenrtbxc23\n" +
                "sxppftvvfx4qvhbrrpcgfb\n" +
                "rmcvzcl8dj4ninenpgjhlblbeight\n" +
                "threeseven7lljggng5two9\n" +
                "four47bnnine2chscshsrone\n" +
                "kxtknjfourjr1pxxkqlxjsix9\n" +
                "sixtwoseveneight8sixthree\n" +
                "8djjznt4\n" +
                "pj48hjlqfour7\n" +
                "onedvpqsevensncd5fivenhftwo\n" +
                "twonls1fivednlbmttzszjczdjfqcspxpt5\n" +
                "11hbdpbbrjddrmlghs\n" +
                "7seventhreeonemsszrjxd\n" +
                "4smtgkzzrxlcslkhlnrft14fbtznvq5six\n" +
                "rdv9four39\n" +
                "four8fourvthreebrnmqmhb\n" +
                "msgrzsdxfxfivecpjqxtphffm3zvgqxkrtwo\n" +
                "1sevenseven3vlcmzlgseight3\n" +
                "three1bkmpjqxsjmjsmlvhfrnine\n" +
                "213sevenfkslf4ldg\n" +
                "fivegflgdlqrfkmh81\n" +
                "jrkqklq5sevensevenddlzbljvf\n" +
                "5zjxsxqpthreeone\n" +
                "fvh6\n" +
                "154xqxjfvt\n" +
                "32fnpjclfgjplmkf83\n" +
                "6nine785six\n" +
                "5one9fiventcxnine37\n" +
                "24seveneightrp\n" +
                "hbd6two1knqnfgcftq839six\n" +
                "6eightzzqghd\n" +
                "fiveptonesixnkslhvpkpsbfltfqnnqjfqjlhthree1\n" +
                "ztdjmvrspdtbqsffive8onetwoblslmlxssjks\n" +
                "876fivenhzmftccrcgvqnssixthreejhg\n" +
                "jpvxbhbrv55ninefive1three\n" +
                "ndpdvz2sevenn\n" +
                "dkzpptsmbfhnnrqqtwodllstjtd87\n" +
                "eight1fivejftckmgxmzbsq416one\n" +
                "2q16ninesevenfour\n" +
                "thdst7fourfivetwosixgfjsnvftone\n" +
                "ztwone8tjlsrsqpnqsxfll9five39eight\n" +
                "threefive757nzddvxh6three\n" +
                "71two\n" +
                "nbgsnbdvqkqr6nvsqhr\n" +
                "four487eight\n" +
                "mgqtnlqxpvbjrgqffourzbtvcxj4xht3twoone\n" +
                "fourninefivefive97hzfxr\n" +
                "4dhrgdrsr4onejzgs5x1\n" +
                "cvnmzrdmtwotlvk4five\n" +
                "7sixzghv5rxlbslsninefrsxht\n" +
                "6lcmjnckbjrtwosevenvmtxcnfvkfqvgzp7\n" +
                "dvndcdmtfxbtznqjrprksseven6twosevennine3\n" +
                "threethreeone11ninesixeightone\n" +
                "dvvcbsix96cxhgjpmqdsixone\n" +
                "five4sevenmnzgktwo\n" +
                "9rlsseventhree6xhtbxdnn\n" +
                "bxlbjtmone15jsixeighteight\n" +
                "1fivejlsevenmbbfksks\n" +
                "eightsix35fourgcptzrfjhkrnfbbznine\n" +
                "seven8sixfive72eightqjmcfjx\n" +
                "seven8616xszttt3seven\n" +
                "53twoone22\n" +
                "onefour9ninetsrvczrnbsbrfstwogkkzs\n" +
                "zpsplntwoeighttwo49three\n" +
                "twoeightseventhree4\n" +
                "eight5twofourgpnlsmppt1\n" +
                "fourccknqs7dndlqhbsdhfmqgr1lvnpmxjtnkshgm\n" +
                "five9ptrnrfdfgdkgxzlr6three\n" +
                "pjxgrrgmfk57hdgclbftr\n" +
                "gdcxzqldf3z2prsmfivenlklnrtbhfst\n" +
                "999\n" +
                "85lctfptljktwobtfnfrttlxrvlfvdnbsm\n" +
                "172\n" +
                "tmrcrhkvnfsixkvzhjxmngcrfmkfpzqcfivermnkxlfive7vtvvmmnfsz\n" +
                "sixseven6two8kfrpjksixeight\n" +
                "75pzmmlvsjn9987dftrvbf\n" +
                "4z1fivethreefive\n" +
                "foureightrdnnpxlnn32knstrmxg71\n" +
                "svzljxbj113zpnpshmnf\n" +
                "hj2hmvp3eight38gxngvkdmnzzzcxjkl\n" +
                "gnrhzjzvrzsix33vqnnrmgtdvvkbsmglckd8\n" +
                "onelgjfczsevenninehkhkxcskvcvnncbpj5\n" +
                "onesevenninethree1\n" +
                "dqqnkzfv9bnine\n" +
                "8sevensjtppblkhh4seven\n" +
                "ninekggzmfsfpbfnvtv3sevenczrhzztlsfour\n" +
                "eight59hkthhk\n" +
                "blskkshczzone7\n" +
                "6one4pffxsgmc\n" +
                "4lrbncnn8\n" +
                "314ninefivesevennine6seven\n" +
                "threeone3ccrfthz2seventwoctg3\n" +
                "bfxknbtwortcfgnrcqsvqfcrxzmlmk83krb5\n" +
                "fiveone8\n" +
                "nine6661\n" +
                "eight8884zbdzcsseventwonexgg\n" +
                "16ninetnzftqzlpvgd2\n" +
                "jxfccks1\n" +
                "sixtfvgpjrvpr6pmsseveneightvbrxnq\n" +
                "6eight5\n" +
                "tdbs3cbfhglpfdnxlt\n" +
                "nbcgkzchlj6pbcx4\n" +
                "661\n" +
                "jcjggnnn1\n" +
                "eightdbtfgpfivecnlmnkrpgf1nine\n" +
                "33bngjpkhgfqp4tl97one\n" +
                "6rkmbdjztnfninecdlhnbnf6ninekmvxrqzbl\n" +
                "465\n" +
                "nfklpzppbq65threeeightsix9\n" +
                "2gddbjlcdkx\n" +
                "kclqnmpsixsix4fivepb\n" +
                "stvlnrfdgcslqmveightbmbgmnzlrq8gfjndq6rsv\n" +
                "sjzcfxn7hs\n" +
                "oneeight32nine2ghx2nine\n" +
                "2lhx9\n" +
                "6eightseven9\n" +
                "three9nineone7five\n" +
                "1nrmk\n" +
                "dccbdjqhvfoneeighthjsmfp89hheight9\n" +
                "sixrfjshf9nhzngkgeight\n" +
                "zsixone5fiveeightsix7\n" +
                "vkthreesevenq42982\n" +
                "2h\n" +
                "8five9jkvqtwo9\n" +
                "lkxvfm7qdhvnkt\n" +
                "8jtttvnmxt\n" +
                "1nine91sixsixfour\n" +
                "8threenmffourone\n" +
                "two2zjj39seventhree\n" +
                "c4eighteight7hssvhvlm2six\n" +
                "9eightfivezmnknpl5eight8seven7\n" +
                "threenine4eight14vzmmhczfhxppqs\n" +
                "seven22fivehgtttqthreeseven\n" +
                "5nineeightthree\n" +
                "hfffcgvnkrp5threevccpjmnfn3\n" +
                "19seventwonelj\n" +
                "4nine8\n" +
                "2sixfggckcdt91three6\n" +
                "9fpztvd\n" +
                "pbm384\n" +
                "rqxzzqtlsx8one91tjmqtcmkxhplcmns5three\n" +
                "four13sixgreight64\n" +
                "seven22four\n" +
                "2six946\n" +
                "nine1767three\n" +
                "mdpvkhvbqstqpskhdxgbzt2zsdvsclhlzbcskckz\n" +
                "1775\n" +
                "pgdbfmvffninezhthree6qlrdkbvqthree\n" +
                "29fourtwo\n" +
                "fiveone14bsnrd\n" +
                "loneight1fourpvcgxjsscssftbfxtkq\n" +
                "fhtwobfnmvjxqzbzctxseven8lhxv\n" +
                "ninefive67rqvgnbt\n" +
                "2fivesevenfive4rhpvklfjz9ninezszc\n" +
                "616vvbxfjplsppgpx\n" +
                "rttqfddgone3rcvdljn88jqrlbdmxgv4\n" +
                "8282eightseven\n" +
                "mkhxlkksgsjrczffqmzzsevenv7seven6zv\n" +
                "5hvkqdnpgtzfjbqrtzx5tncqbmxjpqmmzcf9\n" +
                "llpkjvonesixlnf7one8oneseven\n" +
                "five65qzjtwo\n" +
                "xhcjxj1jghxktnmbxml5bbpklmdcthreedzt\n" +
                "h3sevenonevdnjp5zpzfmch\n" +
                "seveneight1mrrkcpbqd\n" +
                "8one5rn\n" +
                "qbffrljhl48qtg1jhngrrbsdhxl6\n" +
                "ndc5sixcxlcgxpbstwoqfffive5\n" +
                "fpfsqrzfjthreehzbcmhss4fivegbtwo8\n" +
                "nine2two\n" +
                "mddbqdmtcjrkqhv2dxfvdg8eight\n" +
                "jbrkj2llgmg36twocvhmxnb\n" +
                "mhdbsnine1\n" +
                "four1mcvjdkmthmhcsz4\n" +
                "59fbsnx7qrtclvrkfoursdpmhdz\n" +
                "6d6four27zeight\n" +
                "1sevenvjbqrd\n" +
                "9fourlmjqn9rd\n" +
                "gfxsrconexrgdzrhzcsh4six\n" +
                "4one5jhsztrspthree\n" +
                "four5eight2\n" +
                "onebtwo4eightfourhkrsgeight\n" +
                "51kjcqqxrjcnnine5\n" +
                "kprdj25twotwovsdhzgmc\n" +
                "htwone4344five1\n" +
                "dvmkvcfcpsqrh1\n" +
                "9twogzkc572sixhktmslseven\n" +
                "fivefive7qnll7seven\n" +
                "svbpx64n31onevzjhhhl\n" +
                "8fbjkdcttwofourtwokj\n" +
                "6twotwo5zkcnxczszfive32\n" +
                "mbfcmsjmg9hmqngl\n" +
                "ninesixsgnfzsmbgrlxbxjstkmmfxc5\n" +
                "two8fourthree9sdxzvpgseventwonez\n" +
                "td3two\n" +
                "onespktrhrktzrcvdgqvdxgbgctdhjmm7shqcbzvfxhzlt\n" +
                "5zfpfksszthtzxznxgkrpc\n" +
                "8xvmsseven592ssmzjdmz\n" +
                "64fkcmhmqdxnseven\n" +
                "vdhkbktf1seven5\n" +
                "tzfvfour3three\n" +
                "fourl7four\n" +
                "dkbbtpd5qbqgb\n" +
                "qzdlttqfhn8chxxbnplt4\n" +
                "qmd78hqdqxtx2rrdvkvvfourtwo\n" +
                "91mmlbnbs5peightmznzhskfjv\n" +
                "2rftqscv\n" +
                "4oneonenineddktjvjlhone\n" +
                "ninetwo5four\n" +
                "1f36xndmtmmbpx1qzqmdkpbp3\n" +
                "hxsevenjg6fiveeightwodps\n" +
                "4mrndsix18\n" +
                "r6klzqlz\n" +
                "ndbrrsvp9\n" +
                "sixsnkh1gvcnine5\n" +
                "bsstxkninethree5ktwo7five\n" +
                "fiveeight9five7\n" +
                "3nine5sixkqlfrpdpcfive3\n" +
                "lrrqkznlrcmbvdr6\n" +
                "8xklphsevenonetworjgpjlrllgqcrxhlskfhpq\n" +
                "fourmsthcgcxjsixcvnvninebdhttzm85\n" +
                "8gnqnhptgkfivesix\n" +
                "8onenine\n" +
                "fivesixone3kpzvnbrjf\n" +
                "9four54\n" +
                "6twothreefthreefivetx\n" +
                "4nxqzkkbgvthree7qxdhtpjv\n" +
                "six5three2ninesevenfive\n" +
                "3cqkmxnbkkh6tnszgzxqk\n" +
                "82tzncrpvjts7\n" +
                "39one5fivenine\n" +
                "51jrdstpqnjdfbbtjz9three6\n" +
                "nqrmg8\n" +
                "7threesix\n" +
                "one6fsxsflbnfivesixthree5\n" +
                "bxbonethree55one\n" +
                "7onextpttrflql6snmbdtbnvvfive\n" +
                "threeklkjkvqzone2vhzsqdg\n" +
                "eight231eightsix5\n" +
                "cflpngxndfivefiveeight4rjrsfrmmtwonen\n" +
                "three8sdone\n" +
                "nine4nine\n" +
                "two2dxzjxkbb2knvg\n" +
                "bplttc53\n" +
                "69hqtkfivesixtwopffgltlsj1rhhslz\n" +
                "6fbg1scccrkjjsnnhpqmphksevendt5pcdl\n" +
                "9onesixsevenfmmxtkdzone\n" +
                "1onetwocrhcqhrxt7sevenr\n" +
                "sixeightxjjqndfqtwo35\n" +
                "9cqvtmfsqrfqhhbkjgbdk\n" +
                "foursixfrtkpcbxgxx5one\n" +
                "429three\n" +
                "84mxhzmbdk8\n" +
                "nine79\n" +
                "xgntrzninemhxtqnine4ltvx\n" +
                "four3seven6qhrzznzctwofour\n" +
                "5h\n" +
                "16eightninejmddlknrxfone\n" +
                "3gjpbjdone\n" +
                "654twocbczrzjnhkgdpqdd\n" +
                "2xkptbxsixnprkhfslj\n" +
                "19mlqcgbfpdonegdvzghjjb\n" +
                "dnslxvmdlpmlsggq1one18\n" +
                "lbxnz487vjlhhsxvcl\n" +
                "sevengvgkk8mfbplfshlhqnrvbtwofour\n" +
                "djfptvqgmkqgnzdvstwomzpcxfthvzpfsglc7\n" +
                "1nlsztzzcbmqseven4fourdqq2\n" +
                "cqcvkcthreeflhbcsbddg8\n" +
                "sevensvtbtdkfkxzbfqznlh1\n" +
                "sevenksn54\n" +
                "4dzv6\n" +
                "lsixninesevenrxn2seven2\n" +
                "bsix2hqsvvvxvkpbg\n" +
                "hplfzmghmbddz2htfkcfblqcdzfrvqpssbxdone\n" +
                "19sqgxkn8four\n" +
                "64ksmvcseven1748\n" +
                "oneoneonedlmsdc1mjn\n" +
                "7218\n" +
                "3xdskntkmlcldqjgxbgx38rkbddntz13\n" +
                "tnqnvshmhrkxbjvxcvdhmx1\n" +
                "twocrzgfourbvtkcthdkrqpbsevenkfv8zczzszpf\n" +
                "fdkdqfgbgnttlpnjrvnine6dvpdhtchfourbv\n" +
                "qqrznptxjseven9twofourtwo\n" +
                "hpdrqkonetvgfour5onepdk\n" +
                "6eightsixninetclcsllxknspxfgxmlxqddvone\n" +
                "twosixmcbbjthreekclp3\n" +
                "kklgzxnk2eight\n" +
                "zgmnine8oneseven\n" +
                "gmcgzggsixvjzzgrs3gbzmxninezrlcfsphzhseven\n" +
                "7sevensix5fivefourh\n" +
                "rh1qzxvcmqjmtspknine\n" +
                "12threecjltwozchdsfnkmchhgv\n" +
                "vktfhngfb391ghtnrqfourfiveone\n" +
                "9eight46xdxkqtkflqdv59four\n" +
                "839sonesix2btrctxfm\n" +
                "hzpjkvqdfg6three2twocsq8tskmdnvdl\n" +
                "5f\n" +
                "dgmvxqbpbjpbronefivehlf8ls9four\n" +
                "sixm7m8three\n" +
                "vgppvrgdlb26623csvkhsd1\n" +
                "2hjfccgbjnhl8176xkpftwo\n" +
                "seven12vgdnrvmmp1\n" +
                "oneoneone7eighttworvpvsjzl\n" +
                "738one99six\n" +
                "sixrjm3\n" +
                "15six44qndpslhnine8twonehkb\n" +
                "912\n" +
                "3blcn\n" +
                "eight81fivexsbkzcthree\n" +
                "kdqlzbnbnkh2mrpz82six3six\n" +
                "sckfhxxjxfivejgtlmdhc3threeoneightrc\n" +
                "znjgdjd8six6onesevenfour4qpnmvtdnnf\n" +
                "7gnbonesixninehreightlmjone\n" +
                "six3fhhlfgmdlgvhvqctcrxxh\n" +
                "982vbjgptnc\n" +
                "sgfnlppbvfzrmntwo9ggqzsixsixxgqvjvffour\n" +
                "ninenine8\n" +
                "kzfmgls5seveneight2\n" +
                "8ninefourzrgjgrqkxrmjlzqb5\n" +
                "eight7five\n" +
                "fbjt4eight7rnhvfkl5knpvjhqdhvmvczxbvrx\n" +
                "35five\n" +
                "7gzjqslr13qsqxltsninetwoxmhgzhl\n" +
                "threefour2three\n" +
                "onethree45\n" +
                "zvt8nvxctwo6\n" +
                "sevenkfournine1drrmrmljsclgbgsd\n" +
                "jfcnrxjjnbsrlblzpvxc84seven3six\n" +
                "sevenonemt7eightseven6\n" +
                "sevenrddndpj85fzzn4zhvthzp\n" +
                "78zfdbmrfgeightgjtqnx\n" +
                "ninerdqndgffive2dlsblldpfthree9\n" +
                "lvzlfqzsixeightkqbnlv5njjsc4plh\n" +
                "jsqhmbt1xvmkgfbghzdplkxdmgvcrkbngrjlpfj\n" +
                "lfnvhdxcx7twoq\n" +
                "five85\n" +
                "1two3two22bdpbskrlph\n" +
                "ninefc31fnhsnhf5\n" +
                "2cxnrgtlvfvmvvmnfjllshmdvvfc48sevennjfk\n" +
                "xbglffkvrzsmz1\n" +
                "czlrrchbkhmz5qkdbtcjlffd5\n" +
                "eight65sn4\n" +
                "7seven2four99mlpskrgoneighthm\n" +
                "9kfpfgzdjdgxjkltdkbkeightmxteightthree\n" +
                "9bdsbeightjvkrmhdkghfive73four3\n" +
                "xeightwoninehcrsdbnvtwovtbkhtxktjslsix3\n" +
                "15fourlgrsk\n" +
                "5xjqd9\n" +
                "four8ttpzxpnrqnkz1\n" +
                "fourvbfhg1rbrngbgfj6nineldqfxvrx\n" +
                "sdpnkkfive9twodz23\n" +
                "sixone4twoktcx\n" +
                "8rjgbnxsixfivebsnthree2fivenmjxx\n" +
                "fourddtxngtd4jvlttthhmz\n" +
                "2nine95four1six9nine\n" +
                "2gmxtrrkftjfnknknineqjqnscctfourzrqdrgs\n" +
                "flghzhfgmn9tckbpmkgsix9\n" +
                "jg9svtdrmlzm31rsrqvc4mggcj\n" +
                "eightdpvfplptwofdgrkstvh8qseven87\n" +
                "eightfour2fourvzksqhxmlkpkfktmdzpmthreetwonehv\n" +
                "nine86kzqvkjqtjfourmpcggd8\n" +
                "8nstjmtmstcnffnksqh\n" +
                "bvgcmbcrgqfourpvs5xs\n" +
                "8three12\n" +
                "5398db9sixvnvcrztrqz\n" +
                "7one62fourlndnshczz522\n" +
                "qxrhp5eight183tfour\n" +
                "fhpzgkt81two57\n" +
                "ktlfdnbone6\n" +
                "stsninecqxpfmdhk41vlpq\n" +
                "eighttqcc5fqnfour84\n" +
                "25gmh12threeltfnfdrxhh5\n" +
                "57four\n" +
                "mqgdhfour67\n" +
                "37ninetxkddhfive\n" +
                "rzrsskzrlzjbcgthreeghbqhdpxfvgjfqclcf4\n" +
                "fourvone2vbpltlrj\n" +
                "xz5four3nineseven\n" +
                "1szrhcmzkftwo9eight2ltjmgjzcblzone\n" +
                "zlnkddtgsb1sixsxvjxgxp2\n" +
                "26sixpzpsixtwozqff\n" +
                "seven99fzqxfmttfgxm\n" +
                "9twonineonefourpttbgkxt8two\n" +
                "fv9\n" +
                "5qcmjsfk6zxjld1\n" +
                "fkjstnvmchsr9q699\n" +
                "nine78three\n" +
                "4rcs6bhbbgzhsstwomnineksbxfzj8\n" +
                "4fmblhqninefive6qbkm\n" +
                "zsgjbfrjfour1sp3\n" +
                "zbfeightfive1oneonernfd\n" +
                "5bxtfvzczbhtzfourqglqdxsc\n" +
                "f9five7five8ddvseven\n" +
                "23bszpdxfjmzg\n" +
                "fivegctmd3vlcgfgnine\n" +
                "63hbdkxljlq\n" +
                "64eight6eight6gxdpmtnbfone\n" +
                "28xcbtt1\n" +
                "1six5\n" +
                "four289";

        String second = "two1nine\n" +
                "eightwothree\n" +
                "abcone2threexyz\n" +
                "xtwone3four\n" +
                "4nineeightseven2\n" +
                "zoneight234\n" +
                "7pqrstsixteen";
        String secondLong = "9sixsevenz3\n" +
                "seven1cvdvnhpgthfhfljmnq\n" +
                "6tvxlgrsevenjvbxbfqrsk4seven\n" +
                "9zml\n" +
                "52sevenone\n" +
                "41onevfsgvssxnpsix38four\n" +
                "15ninedzhkpfstrscggbqhktwo\n" +
                "rxbfsvhpnjvsixmxfhhmvdvg26rgrfj43\n" +
                "gcbq2sghsv4fiveeightrlhchsfs2hsrjknfz\n" +
                "tworgqpdjzrzf7one\n" +
                "fivefive18\n" +
                "sixfztrcxmbzktwofour3fiveeight\n" +
                "2g4stjrjjmbngvljfvg24\n" +
                "5jkcdxkltwo71\n" +
                "vhpttjh2\n" +
                "3threegmsppjrngfive7\n" +
                "ktkgsvkthreevone2xxrxzgdqpnone2xnf\n" +
                "llxzczt3seventwotwosix5\n" +
                "eighteighthvllljmgg82eightseven2\n" +
                "9hcjzphpktwo76xfpdvnhklzthreejrzkdknhrktwo\n" +
                "fourtwojrvzzctzs5eight2vlm\n" +
                "zoneightthree2hvhfsprqxmlsix7onevn4\n" +
                "56sixssevenfour5twonine\n" +
                "58fourfour\n" +
                "683\n" +
                "8fourninenhfpz9eightptsnnb\n" +
                "gddmrzlpn9\n" +
                "g3qsbqmbhqqp1eightkjggcxpmzgg\n" +
                "6bzjqs7nxpvgtwoseven\n" +
                "271lonepxp2flbmbz\n" +
                "5sgshnrfn9qxt8xsnhtdtx6\n" +
                "cnhflx4sevensixonethree\n" +
                "595six93\n" +
                "6eight8jbtmxdqpj96mqkrdxt9tpbpppl\n" +
                "68qvmgth371lqcrglmvqxtwonfk\n" +
                "mbqbhpmhspsbbxgflg98zn\n" +
                "8oneqzvdcrh\n" +
                "kb6\n" +
                "mhgvpmfgjfourfourtwo4\n" +
                "81mvcgqxlktbpkkrsgbdgeightbqn65\n" +
                "hlbhthree1seven9\n" +
                "vqczmtvqsnd3sh63\n" +
                "qrzngvmk8\n" +
                "chpldqtkhqbvdvmnqd5\n" +
                "6three6two\n" +
                "sevensix4tjvkcfgpone98\n" +
                "96zgpcq9four\n" +
                "cbvksjgvvklhnksixfive7kmmxg\n" +
                "threeljfr1vzskggfvjsccc\n" +
                "8pfourthreetwosix\n" +
                "l2sbdcvngvmtzrtq\n" +
                "hjdxfj94\n" +
                "2hbhfbjfteightnr5sixfpfjkn\n" +
                "2sevenjqlpprggjlkddqv9oneightpj\n" +
                "fivebfmkdrrrdkclkscqmtwo6five7\n" +
                "fourrp8fnbp9d1fl7\n" +
                "six8pffqfpjl2nine\n" +
                "91sdjlghq5\n" +
                "fivemrmcnjmfcnck2\n" +
                "v1\n" +
                "78htfvqsztlsixeight\n" +
                "5zpjtbgpkvkxbgpsp3cgklflkhdteightwortv\n" +
                "mcxqfgxt49sevenone9\n" +
                "rt2dsvpf\n" +
                "9dzxmfour76six\n" +
                "tsbmbdrgmzsjeightonezqhqb5qn\n" +
                "seven8zllmz\n" +
                "373onefourthree\n" +
                "1fourfivezthdcxfr\n" +
                "996seven2four\n" +
                "8smnghninezczdlzxxgf\n" +
                "7cbqfzrmhxdmrdr94tz\n" +
                "6vstr65tfivelmhjshhj\n" +
                "248fourlckvrtnzz4sxdqpgkvh\n" +
                "zfivejfgfgdhfrhr6\n" +
                "one2tworsmtnzfjhvvqjnp\n" +
                "5threefourjsnfzninethreejrknzfn\n" +
                "seven9nine\n" +
                "gthree15fivemzpnqgttcq1\n" +
                "fivevvvkgtvs3four4\n" +
                "five121three\n" +
                "7fourn\n" +
                "sixdnineqvfqglmn98516\n" +
                "ninesixrppx4\n" +
                "threesevenxbskhlqbone276\n" +
                "fivesixfour82\n" +
                "tmdnvgrkjxfour9\n" +
                "61nine\n" +
                "vtxpkcgb48jzx8rgeight7\n" +
                "twoonetwo3\n" +
                "four167bnbdtxq4xvdgckkpb2\n" +
                "xgbxvx7ninehmvqlldtxls88qhztfldr4\n" +
                "5qxsfdchthree41\n" +
                "fournb5gfqzfrlnc5fivethree1\n" +
                "t6fourh3\n" +
                "ninefgzksevenseven5sbcpnczgflqptjhk\n" +
                "6three4\n" +
                "5tnplthreeeightvsk2fivesix9\n" +
                "three8hcvnmvbhbtwo\n" +
                "6jnfourdbcgzgfzczbc\n" +
                "z53\n" +
                "fourxzhgjfrrbmkcheightfive7seven8oneightb\n" +
                "2fivehkhnbtm\n" +
                "rptgktsnzvsslcvfsevensixfive72\n" +
                "95chcvtxv4\n" +
                "ninenldnphcpn93fivetwo7\n" +
                "threeeight675vmhvgtxxc2bp\n" +
                "hfdmpv6\n" +
                "xpffsljjcm27\n" +
                "8sevensix8\n" +
                "7hmszcvzpf9eightqqxgjdnhpfour68\n" +
                "2czrnzdpxsjsdldcxq2vzgfrthsssix\n" +
                "four5bdxdnvtgcbdzzsxjdlbckninetwo5\n" +
                "35fourfive6\n" +
                "z5eight3r84hvptgskcclbsgh\n" +
                "2eightljldmconeeightgvhm\n" +
                "4sixsixsixfourthree\n" +
                "tnnthreelfmhone1onepfivevdg\n" +
                "8nine9lmpptxstrrbqbjrjtm4seven\n" +
                "2ltqd9mnrbhcsprz\n" +
                "two5ptcjzbqnk2spvlcxqvglndgvrlm5fiveeight\n" +
                "52sqstnqpdeight55\n" +
                "2nvskvthreeqhkqvjzqrk1\n" +
                "gbkqz127four\n" +
                "8zmngr5381rb\n" +
                "klrlqvkhslvbxdtwofour4cmlpbdm6\n" +
                "eightninenjnmc8zrnrltgfmfour\n" +
                "38sv7\n" +
                "eightvtkkmhhninebmgdvconenine7sixjkdzxcr\n" +
                "h14bdgvknbnjq4fv\n" +
                "74svtwo\n" +
                "7three5sixone4\n" +
                "zseightwo6five\n" +
                "shkznseven5ninefivefour8\n" +
                "mcmztmrgctqszzpqs8tworfvkseven\n" +
                "onejjmdfour15nine4\n" +
                "7bxqxxxvlthree4tb9five\n" +
                "twoqzpx6hj\n" +
                "68hbdjdd45two\n" +
                "68\n" +
                "4hxlfbgvtdmbhnpfzxpnltfivemtmczjcbffour4\n" +
                "fourseven4hfffmtqoneglgnnsrqsmbnxr\n" +
                "dhbbmcxtv7five9ffjjcmshv31seven\n" +
                "foursbgvhgbggnine6three4zznzcvmxxqktpdhff\n" +
                "681cvdh\n" +
                "3ninefivefive\n" +
                "jg4dnnxzdtwoqdbvfsix\n" +
                "g4dbeight6rkc\n" +
                "236bjcppxmlnine\n" +
                "5crthreefive8\n" +
                "6twoknqfbmeight5c\n" +
                "64eightrkvvtjtsonefour9eightwoqxq\n" +
                "sm7sixfivexbrkvhtl9\n" +
                "threeninetwotwo1one\n" +
                "tjjeightwoj3gsdmdseventwo1\n" +
                "63sevenk4blssxzkcq29ztjlnx\n" +
                "ckpleightxgngnhkj2threem\n" +
                "8knckxzrfbbpxldzninennnmkxkzzstsflv9two\n" +
                "rmldrlcvccgdbvdnxvqr3ninefznpqrrtd1cfpjrvjzs\n" +
                "5twojdflbxnlslnsjtklqkrbklvkthreejgxkfzeight\n" +
                "sevenxfpzvss6\n" +
                "one61\n" +
                "2seven7eight\n" +
                "fivefive5fourtwo9vjmxmtpv\n" +
                "4pxfour\n" +
                "twofive1eight9ldjbfbzhhffdb\n" +
                "onefive7four93pjchnkrzvz\n" +
                "4194hgfslhdczj1ztjtnccpjseven8\n" +
                "sixtkjmtcthreezjfcgbdhvqlmbpzmc7\n" +
                "nineeightvnd55sftvbf4sevenrkgbjskxbj\n" +
                "kqoneighttpqcnsphsfour7eight9sixthree\n" +
                "5foursvfsztnfivekkkftdfbptmrgcone\n" +
                "sevensix8one5zjlfcrqzvp\n" +
                "1hmvpbhzcbgbgvdkblnhgklltxx\n" +
                "55xszsjgbd2fk\n" +
                "hdrhmddj6ninebcfhbd\n" +
                "f91six\n" +
                "3tltgktntqpkeighthbqhlxcqnffgbfvxrkmr2\n" +
                "3jthree\n" +
                "2eightplclghthree\n" +
                "771\n" +
                "5gccqqmzmx81twob\n" +
                "6pgnqbsqglk44mvslnxghckcbtffxvkq2\n" +
                "twooneone5\n" +
                "twohbxsxj2six826hlkdjnnz\n" +
                "17tbdmntksvn89fivethreeseven\n" +
                "sixplznhmbgzmlh3six1\n" +
                "h2kvpbnkcxrssevenfive\n" +
                "jhpmnksix7fgnbhgv8fztxfrpfvmnrvhzr\n" +
                "vskpbnine3vjqdlmv9\n" +
                "vmg86ht36sbnzphxfive\n" +
                "klqxeightnine6\n" +
                "4nfninelzshl26\n" +
                "zqsb243hfdtvgx\n" +
                "two9tzcrmrsix81xsgvldl\n" +
                "ggqeightwo5bdpqtjkgzdclxsqptwo1eight1\n" +
                "pvfzftdxqzfourmmbzlbzcfsevenfivesix5\n" +
                "fivelt5fivegshvshpvkpqlddmfj6\n" +
                "cjpzgsvgsz7kzcpr1sixfour\n" +
                "8two4onesevenseven7v\n" +
                "ztwonefouronezdvggfive8eightzflpvlnxfspgrtwo\n" +
                "one7tphmqvfltwo\n" +
                "49seven2three\n" +
                "9rntqtxseveneightgflqzkrxhglrnvrvz1\n" +
                "four6nine7\n" +
                "5nine3\n" +
                "4ddpkhft12hrhjvbtdxthree1tpknk\n" +
                "7k\n" +
                "fmlrpkxqktzdldrs84onefptgdjspldljvnine8\n" +
                "oneseven4nineqbqlbxf2kqnpr\n" +
                "ffivetwo97mp\n" +
                "47h92ffcd6\n" +
                "two7tcjvxdvctfivepcqxjnzfourfcndmdmnjseven\n" +
                "cjdjxmnmpqr6cqvcscdpg\n" +
                "onefour95\n" +
                "seven9onenine\n" +
                "trpvv6six64kfmxqrdvbsevenhqzk9\n" +
                "tsgpcfxsgsgmhd7rvfz\n" +
                "66788\n" +
                "five26b\n" +
                "chcbxone1\n" +
                "6mrlfkqjssdxbtzkshvc8hjltjjxthkl\n" +
                "four5sdsevenvztqmzkm21threenine\n" +
                "snxrlctcztlbntnxkpmbs2\n" +
                "652nnhvz6vcgx\n" +
                "2zrxljdgsnnfour5fourp4\n" +
                "85lzkjln55239\n" +
                "51fourrnbkb4\n" +
                "xbvsjmgsjdvhjpxdjhl1\n" +
                "6sevencfhtbm4svgpzeight8three4\n" +
                "827cclvxpdgqlhrjvrgxbxthree\n" +
                "8pgqr\n" +
                "three2ninesjztqjdhdv\n" +
                "538one59one\n" +
                "6lcmxone4ninehzzb13\n" +
                "phckzkgtxdcnine8onefour744\n" +
                "five61\n" +
                "skbknb9qknrlszdt\n" +
                "fivenine6jnxfsseven7\n" +
                "lfj2onethree4198\n" +
                "bb9\n" +
                "kfljcb5zssbrlzml\n" +
                "twohmspvflmxnine2eight8\n" +
                "4onegfnxxqpqnfour7\n" +
                "qvg7seven4\n" +
                "85bheightghccknine1three\n" +
                "fivedpthreeseven1fiveseven2\n" +
                "6nine3gzlbtvtvlnine6eightmdn\n" +
                "seven3seven58gzmdjmchdrzxgkgbbfrf4\n" +
                "2lxbnnsixgdcv6hrqjnfhdmz\n" +
                "8threefiveflbfmthreegtvckvpxkd856\n" +
                "jbnkkbvfivexqzm238zxvztfl\n" +
                "68kglf7\n" +
                "9fivetzjsixkvfrngxbfbbjpd69\n" +
                "ninejgz82fivenltntmfs6xpxc\n" +
                "fourlseight3qrrrrddzlone\n" +
                "seventwoqfkj2qxzddcgtb348\n" +
                "xgjddt5\n" +
                "q8bfhspkgmsevenninevdqmlzxznhmdlg\n" +
                "qc2sqqlkfrkj652xpgzjskr3four\n" +
                "two3tpl1cvmldrrghr\n" +
                "qhoneoneseven9zfivevrkkjhtdf\n" +
                "ddjczzpcvkksjzdcmxkhmbds2\n" +
                "qnvgskzdb3nine77sdvfhfqsnv2kjffgsvz\n" +
                "six8three3vbpnkb\n" +
                "rgjmvgtgfour36qqbqznkjv78cbpdqb\n" +
                "fournshtzbqfourthreefive8hsbpflngrvzdhone\n" +
                "toneightone9four\n" +
                "fourkkxtzpfivetwovnvxmtkeight4t9\n" +
                "tbxlvkc5vgcmdckzv\n" +
                "7threethree\n" +
                "9ntqnzpldshfqlc2six\n" +
                "8zs7five\n" +
                "3threethreentqthree\n" +
                "jmxjl4four5\n" +
                "jnmrhzpdvbvvg9qcxjjmv2msrszndl\n" +
                "onezjrkeight4two2seven\n" +
                "32jlkhszgnkklbrsgpplphh\n" +
                "1gsdqlbgt5eight1\n" +
                "219\n" +
                "93gcgx2twothree9xggt\n" +
                "5fivenine1fiveplgmlffsvzbtqpb\n" +
                "qv7lthszlgxeightnine\n" +
                "7sevenmhmkcrkkq\n" +
                "mxmmgqp4rptkbhfourvjh\n" +
                "3mrmhgjmdv6pvfkbmconelmlckqkxjfiveznxg\n" +
                "7one1kbjnmtpskgsix99\n" +
                "bsvjlfgrcvvhmnfjzktdeight9914\n" +
                "csfrjtwofivebcrcmggfpfsevenlmhncfb1two\n" +
                "3five1vphfournine1kvfvzrtm\n" +
                "nineeight3vxrdvttwo\n" +
                "snncrseventwo5sevencjgl\n" +
                "ngmgxnlsjjhvqpcxjshninesix63\n" +
                "4threeone2twotzsseven4prqdrnjln\n" +
                "fivegfmn391\n" +
                "three5xflqlnrjgfpzt5\n" +
                "28two\n" +
                "six729twoeight7\n" +
                "eight11\n" +
                "sevenseven1fqcsevenonekrgxmone\n" +
                "8rvlj62\n" +
                "one3ninethree\n" +
                "89s6two2twofive\n" +
                "pnhhshxqb312\n" +
                "vlnj5eight9\n" +
                "5seven5eights3eight1\n" +
                "6kqvkbjrfveighttwo6\n" +
                "5twofour\n" +
                "ztnkthreefive1fivetwovqjpx3three\n" +
                "qs2\n" +
                "2vft3\n" +
                "zjr1zjpxndcsc\n" +
                "76threesix\n" +
                "1four88n7\n" +
                "9mrrkjzlxdc\n" +
                "1ll89\n" +
                "fgvcseven81\n" +
                "4789vtvtcseven\n" +
                "2lcfbmqcqt\n" +
                "5sixonefive\n" +
                "cdoneight1onetwo96lpllgksff4hrzjkxng\n" +
                "gntghdtwo1\n" +
                "eightninefpdttgflvr2\n" +
                "8zcnfm4krxhfive67seven6\n" +
                "2hxpgvxgsmc\n" +
                "trlvltteighteightrzkxntpdtpl24\n" +
                "hkttzcmnck7s1seven\n" +
                "sevensnmhgdxpbksngnflnthreemlqgdvphzk5tvmzjvdzbcseven\n" +
                "eightpsbcshqcbppkgfxcnrgtwoeightfour6four\n" +
                "53xktsrztnxninehpjjjktqnsixfivefive7\n" +
                "sevenonebkdseven1seven\n" +
                "11sixzdqbbppninehhkpxdbmlv2chddf\n" +
                "3one3fivesevenlljjmxvzbcnqtszvzspsevenb\n" +
                "1txlrnsb1vq28kpvv\n" +
                "1two855\n" +
                "2lxzhcjl1qfslvldkpdcxf\n" +
                "9seven3fcqtzfive\n" +
                "eight4phtznrb69xqbmxmdvxnsstnine\n" +
                "eightfive2sixnhxcffkq95\n" +
                "five28cppfive1two6\n" +
                "p8\n" +
                "kn8\n" +
                "6hvzkkr4nine2seventwo4\n" +
                "39134\n" +
                "dztwone3kqlbbbknfive\n" +
                "xvvdhddonekcgqqqzgxhlg2seven\n" +
                "237rhppmlcmhsevenvnjxhzfnzbzrsdl\n" +
                "1kgq1qsphhpcdeightjnfsdggnlnckgfbj2\n" +
                "bnvpzxtnt16two\n" +
                "mkhvcrfqdtwo3qfmhs\n" +
                "1hkjncflcz5four7bbgpgcmnv94seven\n" +
                "7seventmmhfgngfxt4\n" +
                "98238\n" +
                "3zmnhxqjqhjtptwoqtptmxfdp3seven\n" +
                "bkqxlrtf4\n" +
                "onefive8tvb6fiveone6\n" +
                "1four3seventhree5mvsbsdjz\n" +
                "jtjsjflv5gxvhdgvrbgbdcjjtchkvmf\n" +
                "sixthreefcrbqzqs7psczkdc\n" +
                "dc572twonejgl\n" +
                "2xkrpz9dfslbjvmbdkgsixhkgcvdgktq\n" +
                "five114\n" +
                "8two85\n" +
                "9fbh79mqbfsxcnn1two6\n" +
                "6one9fivetwo\n" +
                "gsjljnkhhvqlmmvcthreemfcbnjsbkvzzsnkb7\n" +
                "nine49twojdqjsfbzsixrhbjhn4\n" +
                "3threesix1\n" +
                "52six1twoseven\n" +
                "eight9dbb6hhjnt\n" +
                "gsnqmninefivefbqcrlneight1\n" +
                "jxczccqqpxbcq8\n" +
                "1ckvkgqtvqrpvdrfivejjhhfkxvvhfm\n" +
                "sixdxgvgglfh4qzczn8jpgqmgbzkmcdjfnhmh9\n" +
                "eight7nine9\n" +
                "tzqv6fivefourhfz\n" +
                "sixnine2vkmdnkgtgnbbkcxvvsc2bf22\n" +
                "78two41\n" +
                "srpeightwovrhmbnkpnsix1\n" +
                "fourninemfcvlstbmflzqf9lgvlvrlff2srxpzvrp2\n" +
                "kcgtwone9eight\n" +
                "7three1onesix1m3\n" +
                "rgk2fiveeightthreegckdbd9dml\n" +
                "sevencx9onenineeight6\n" +
                "9ninetwocb4thttbkqj\n" +
                "five26vrc2krtfivejpgdmtjg\n" +
                "2ninethree7cnxbkpvthreefiveqclhc\n" +
                "98seven28\n" +
                "onetwosevensix9three8\n" +
                "sevensix2\n" +
                "ninesixlrdgpbrzs7onedrtlqpfour1\n" +
                "pmvxzronexxxvbdrjr7\n" +
                "15eight\n" +
                "crksmfive64\n" +
                "onetwo6fivemqkddjfxndjfpzmeight5xzk\n" +
                "gq3ninetwo9\n" +
                "8mgkvbpmbzpd7\n" +
                "xfbvzlbpvb79\n" +
                "kkbrvppqcg5\n" +
                "94dkngltfzs98\n" +
                "rchmjsrh7onejcknbl\n" +
                "9threesixxrbzjt\n" +
                "3963seven48sixeight\n" +
                "98992\n" +
                "7zqd\n" +
                "sevenseven814htznfour1\n" +
                "ninefivedfrtwoone5\n" +
                "qzgrrng8six\n" +
                "3742zsgbqgfvzlgsgfmxql86eight\n" +
                "seven7zdfrhonemfhcfmclxj25three\n" +
                "8pnhpnsqxh\n" +
                "62seven\n" +
                "eightpfgmmdg945ksctbstnh6cdxvgqbl\n" +
                "932zsnvmcone1ktfqfmbnsfive\n" +
                "dglzhqjthreemzpm78\n" +
                "one7sk13ghnmvsrprg\n" +
                "jdvzccvczspscxj5rzzdqdd44txvprhqx\n" +
                "sevengmtcflgvpzonecvmbtgknine7kngpspbg\n" +
                "xmqk6jmhmdtvh2kbchmsgpjrv2four\n" +
                "tntsjnine3jksrrvone\n" +
                "xfzgbzfive3ninekmnjrlqkzq96foursix\n" +
                "3xbcth723\n" +
                "zbvtsrxh94s\n" +
                "threesix8mjchcpvmdgfive17xb\n" +
                "8eightnbbzhfhf4fiveeightmnzqldztsnfour\n" +
                "tkglxsb6one62rhzggrtgqxqnvjzfmb\n" +
                "gtj2onempqp34qfjnlxtztvjvsv\n" +
                "2eightzxdgc3\n" +
                "32dgskjkh2\n" +
                "sevendnvrcm5166\n" +
                "5knxkkjh5\n" +
                "fssjcvvckqjrcghcmlrkcvxl22\n" +
                "2jbhdlfjtbfivetkjbjmtrgxrdmxsix\n" +
                "fivedm8pzjfngzfsk35\n" +
                "two31ldnvx\n" +
                "5mfive9ggkq\n" +
                "vqdhfsfkrpp44trqpnkqsdxvvdxc\n" +
                "lkdqckshmn1rgrvtjqj\n" +
                "ttwoneqzmsxzskbbnkfh8onespphhmsix31\n" +
                "jknbnfvbf1snjscz5\n" +
                "sevenvjn9\n" +
                "ninetjzhbdjsffthreecfctlsfrz2\n" +
                "6ninedqmxfqxssbhrrffpdhjvhqtkxfour9\n" +
                "6tlrxcvhtllkrhjxqt3two3\n" +
                "eighteightfive79\n" +
                "5sixfive7bjlkninefour\n" +
                "xrgrxsvm5bhcmzggbkrljnssxgpgdlv2four8\n" +
                "1mxlnrtsjgdlcsncktrsfour\n" +
                "8xtkgjjbtjfnc62vsshkjp\n" +
                "91twoninetwo\n" +
                "ninefour5nbnnzhtfiveggrjf7zqzblbml\n" +
                "sixfour42rtbvlpcnv4\n" +
                "oneczchdtwoglj9279\n" +
                "jfvv5rdkpzldsxh\n" +
                "ninexghzhdqk67\n" +
                "gnllbntksevenseven7sixeightvgnfd\n" +
                "qzqjxcqrs8fivesevenrnvnq9nqnchpjpmfkgtjqcsvtv\n" +
                "6sixsixspzppcstlhqlssvt\n" +
                "4hhfndc17rjrrzvbjj\n" +
                "xm6sevenseven2fivendnn\n" +
                "threesixd6nrxmxgcbjfrtlmpkjnoneshmrn\n" +
                "ncnpmsixfour4two\n" +
                "pqvz9fourkkmfvzbjqbfour\n" +
                "szspfourhsqkfkfcndcnineone5khdb\n" +
                "six29sixlkfbphnrzcjl\n" +
                "cdtwonenine73\n" +
                "mtlqpjcqcseven29\n" +
                "8onekdvdmjbmbjtdngxhjjchdv7bvsbjqszlhvht\n" +
                "fivevqnjsvnhvnine1kxcsjmzx\n" +
                "6six32twonine\n" +
                "nnsix5fcsrdvoneightcn\n" +
                "11rzzpnrtnsevenmvnhgrsgngthree\n" +
                "3fourjfonefoursevenbbfour\n" +
                "fiveclfour7seventwoeight\n" +
                "4zvzlfive7hkzhbqrleight8\n" +
                "4eightthreemthreeq\n" +
                "66nine\n" +
                "dlnm59eight\n" +
                "fourthreexvgpp7\n" +
                "85sixfnrjqvmzmtbpxttrn\n" +
                "one2seven\n" +
                "63fourztwofdssrbjbcvhltg7\n" +
                "fdstgbg1qdznxnvftfvfnr6djj\n" +
                "5dcmbkrlvsrfvbdfqfour\n" +
                "xp6fourrcfxdnktdctwofour\n" +
                "9three4threeone6\n" +
                "8pjzglttwofive9\n" +
                "2gsix9sixthree\n" +
                "ptwofive3t\n" +
                "4hqkqzjkqddnnhxkrfnhgbkthreethree2\n" +
                "threedthcktqkcthree22\n" +
                "2gdlntwoseven527tzxbzkdjbv\n" +
                "6hbxrgxzcnlbnz6\n" +
                "ds7mvjbvfkn\n" +
                "sixrpd7eightfour6\n" +
                "qfoursspgghsflcrvqeight6\n" +
                "94hxsj5\n" +
                "bhhhnfnnkninexnjtjxrphrkc9mdmjp\n" +
                "pbttrcplcsrldftsgk4991threepcbhxxfrgjddpz\n" +
                "6four1fgjmjcnj3nbxxnnxhjhv\n" +
                "6onefourshbzqgxjnhpmz\n" +
                "9onedvscbrdj5\n" +
                "jgjrpgcjztvkqseven8sznzl16dzrhmhnq7\n" +
                "ctlbzmcctmkzpqtsdztbmllqnoneoneonenine28\n" +
                "znkkbdsix23msxkcs\n" +
                "seventwo365one2nlmlbgh1\n" +
                "mtzthdjtonezfsixms5mxjpftkd\n" +
                "onenine8ksxnslf16njqldnnkjx\n" +
                "pzjl78nztcgnj211zxnmhxzrjjh\n" +
                "twozkf3fiveshpt\n" +
                "seventwo387bnfsix\n" +
                "2xvvtzthreexjfxxg4seven\n" +
                "8vgjxlvjc4twoglhmpgtsbfonethreeqbpcfbmz\n" +
                "mhlgjlbm68rmeightnineone\n" +
                "threezhldnzscqfour9seventfkj\n" +
                "cnprmbrprlhmonesixlksvgzseventhreehdzh2\n" +
                "smp215344two\n" +
                "5nineonefive8sevenzvlfrprdq\n" +
                "rvf583\n" +
                "four8nine4crzpff\n" +
                "rhnsqgnncnjzhpx297qmj18\n" +
                "oneqlx716452\n" +
                "mg3zptnqbm\n" +
                "4ssgqpsevenznzlnnsbjpxkfvlkrjckxrhqsevenzrgjlkcffb\n" +
                "six9fourshjkhspkcffiveeightqqkvktvjsmmnfrthree\n" +
                "sixdljbtwoninetwo6ninesevenn\n" +
                "kcjqfvldclrmsd52qn\n" +
                "352one\n" +
                "7nine7\n" +
                "9fourjcveighth\n" +
                "5twoz73\n" +
                "bbsvvbjc1one5gtts3nine\n" +
                "four2six\n" +
                "7nine5\n" +
                "nxjfthslhc2sspz\n" +
                "69onethreefour8nq4eightwoqh\n" +
                "8mfpmmthree6eightbksq7\n" +
                "98bzjlfjm\n" +
                "six541threepklngxmfthreevvkdgxpfour\n" +
                "seventhree4ninesix\n" +
                "7ninejkcxsixsixlvffhbkjkfive2rdnd\n" +
                "9flxnpfddx68mfgnkkdqlonenblbszdvvbfour\n" +
                "threemfk22vf\n" +
                "threeninemh6\n" +
                "88six\n" +
                "4eightrtthree\n" +
                "4rkjjgppc2lkvnhbnhffnrvqsj8\n" +
                "65gdpxxz\n" +
                "5fourfour6\n" +
                "six9m9eightfour\n" +
                "21szgzbcg\n" +
                "krzfvtsgp3\n" +
                "six2threethreebskteight4twoeight\n" +
                "58bjrnzbqg\n" +
                "8eight4four3\n" +
                "four6qcrnthree2\n" +
                "j8nine7gqlvtqxlzdtcbonetwo\n" +
                "sixvlthree55seven37\n" +
                "48sevengfgzczbg82\n" +
                "eightsix2qsqfgmsrscfive\n" +
                "zpbxnxbnmjthreebmksffpkd7seight8nine\n" +
                "vfvhcvnsevenkbnhxxhhc3csk79\n" +
                "147threesixtwo\n" +
                "hldlvjninehnqxd7fiveeight7sixkkbmjxnjf\n" +
                "six3gjbkbpgzdszl3f\n" +
                "donethree3seven7xvfgnthree\n" +
                "3lgpzhzmfftwoeightjhlngfn6five57\n" +
                "5fnfl6vkncfsrrrsmxsl\n" +
                "7ss\n" +
                "five6gsncdxsixnhphl85\n" +
                "3rklhfbkhfour884\n" +
                "xsjseven7\n" +
                "58mxlmsevennine7cssix\n" +
                "1jnbbfourv\n" +
                "r21kstwo\n" +
                "zrqlghpcsixeightseventlnpnxpzv3\n" +
                "887\n" +
                "zeightwo3xzjvmqxpjtbvj\n" +
                "1brtqrcvbrrqsqbpsl1sevenseven22\n" +
                "4qcddseven\n" +
                "mg3xxlgdkblgg1htdjtfthpv\n" +
                "9eightwoslp\n" +
                "ggqvtwonsfsevenfour73ccmzkz1\n" +
                "7rfjfqh9nine\n" +
                "gnpnrzzkdtfcseven45hvv\n" +
                "34one1\n" +
                "xzkfl9fivebxhcxrmfzszonekgzcvk1six\n" +
                "8pzscngsixsrtjqqlk25ldczspzfdxrzhh\n" +
                "zktjxcb72twosix\n" +
                "9mvtk5jqhtwo\n" +
                "two82klbfdf\n" +
                "xstrdlsmx2onesevenrmgpjlrtfsfourfive4\n" +
                "four1djgssbq8sixfive\n" +
                "j1jkgzrjmnfxonejsvgzznsevenprbqbjn\n" +
                "two65ffglkhgqb8xdxmldhtllj3\n" +
                "lqqqsrjf27four9dgpjcgz\n" +
                "fptvlnfzpfm99eight8five5xtgqt\n" +
                "sgrdlpplhb2six6\n" +
                "one4811eightrvkbchcngmone\n" +
                "bcsv46dgxglfxsrn9two\n" +
                "spshpxtwo6c\n" +
                "1sevenrtbxc23\n" +
                "sxppftvvfx4qvhbrrpcgfb\n" +
                "rmcvzcl8dj4ninenpgjhlblbeight\n" +
                "threeseven7lljggng5two9\n" +
                "four47bnnine2chscshsrone\n" +
                "kxtknjfourjr1pxxkqlxjsix9\n" +
                "sixtwoseveneight8sixthree\n" +
                "8djjznt4\n" +
                "pj48hjlqfour7\n" +
                "onedvpqsevensncd5fivenhftwo\n" +
                "twonls1fivednlbmttzszjczdjfqcspxpt5\n" +
                "11hbdpbbrjddrmlghs\n" +
                "7seventhreeonemsszrjxd\n" +
                "4smtgkzzrxlcslkhlnrft14fbtznvq5six\n" +
                "rdv9four39\n" +
                "four8fourvthreebrnmqmhb\n" +
                "msgrzsdxfxfivecpjqxtphffm3zvgqxkrtwo\n" +
                "1sevenseven3vlcmzlgseight3\n" +
                "three1bkmpjqxsjmjsmlvhfrnine\n" +
                "213sevenfkslf4ldg\n" +
                "fivegflgdlqrfkmh81\n" +
                "jrkqklq5sevensevenddlzbljvf\n" +
                "5zjxsxqpthreeone\n" +
                "fvh6\n" +
                "154xqxjfvt\n" +
                "32fnpjclfgjplmkf83\n" +
                "6nine785six\n" +
                "5one9fiventcxnine37\n" +
                "24seveneightrp\n" +
                "hbd6two1knqnfgcftq839six\n" +
                "6eightzzqghd\n" +
                "fiveptonesixnkslhvpkpsbfltfqnnqjfqjlhthree1\n" +
                "ztdjmvrspdtbqsffive8onetwoblslmlxssjks\n" +
                "876fivenhzmftccrcgvqnssixthreejhg\n" +
                "jpvxbhbrv55ninefive1three\n" +
                "ndpdvz2sevenn\n" +
                "dkzpptsmbfhnnrqqtwodllstjtd87\n" +
                "eight1fivejftckmgxmzbsq416one\n" +
                "2q16ninesevenfour\n" +
                "thdst7fourfivetwosixgfjsnvftone\n" +
                "ztwone8tjlsrsqpnqsxfll9five39eight\n" +
                "threefive757nzddvxh6three\n" +
                "71two\n" +
                "nbgsnbdvqkqr6nvsqhr\n" +
                "four487eight\n" +
                "mgqtnlqxpvbjrgqffourzbtvcxj4xht3twoone\n" +
                "fourninefivefive97hzfxr\n" +
                "4dhrgdrsr4onejzgs5x1\n" +
                "cvnmzrdmtwotlvk4five\n" +
                "7sixzghv5rxlbslsninefrsxht\n" +
                "6lcmjnckbjrtwosevenvmtxcnfvkfqvgzp7\n" +
                "dvndcdmtfxbtznqjrprksseven6twosevennine3\n" +
                "threethreeone11ninesixeightone\n" +
                "dvvcbsix96cxhgjpmqdsixone\n" +
                "five4sevenmnzgktwo\n" +
                "9rlsseventhree6xhtbxdnn\n" +
                "bxlbjtmone15jsixeighteight\n" +
                "1fivejlsevenmbbfksks\n" +
                "eightsix35fourgcptzrfjhkrnfbbznine\n" +
                "seven8sixfive72eightqjmcfjx\n" +
                "seven8616xszttt3seven\n" +
                "53twoone22\n" +
                "onefour9ninetsrvczrnbsbrfstwogkkzs\n" +
                "zpsplntwoeighttwo49three\n" +
                "twoeightseventhree4\n" +
                "eight5twofourgpnlsmppt1\n" +
                "fourccknqs7dndlqhbsdhfmqgr1lvnpmxjtnkshgm\n" +
                "five9ptrnrfdfgdkgxzlr6three\n" +
                "pjxgrrgmfk57hdgclbftr\n" +
                "gdcxzqldf3z2prsmfivenlklnrtbhfst\n" +
                "999\n" +
                "85lctfptljktwobtfnfrttlxrvlfvdnbsm\n" +
                "172\n" +
                "tmrcrhkvnfsixkvzhjxmngcrfmkfpzqcfivermnkxlfive7vtvvmmnfsz\n" +
                "sixseven6two8kfrpjksixeight\n" +
                "75pzmmlvsjn9987dftrvbf\n" +
                "4z1fivethreefive\n" +
                "foureightrdnnpxlnn32knstrmxg71\n" +
                "svzljxbj113zpnpshmnf\n" +
                "hj2hmvp3eight38gxngvkdmnzzzcxjkl\n" +
                "gnrhzjzvrzsix33vqnnrmgtdvvkbsmglckd8\n" +
                "onelgjfczsevenninehkhkxcskvcvnncbpj5\n" +
                "onesevenninethree1\n" +
                "dqqnkzfv9bnine\n" +
                "8sevensjtppblkhh4seven\n" +
                "ninekggzmfsfpbfnvtv3sevenczrhzztlsfour\n" +
                "eight59hkthhk\n" +
                "blskkshczzone7\n" +
                "6one4pffxsgmc\n" +
                "4lrbncnn8\n" +
                "314ninefivesevennine6seven\n" +
                "threeone3ccrfthz2seventwoctg3\n" +
                "bfxknbtwortcfgnrcqsvqfcrxzmlmk83krb5\n" +
                "fiveone8\n" +
                "nine6661\n" +
                "eight8884zbdzcsseventwonexgg\n" +
                "16ninetnzftqzlpvgd2\n" +
                "jxfccks1\n" +
                "sixtfvgpjrvpr6pmsseveneightvbrxnq\n" +
                "6eight5\n" +
                "tdbs3cbfhglpfdnxlt\n" +
                "nbcgkzchlj6pbcx4\n" +
                "661\n" +
                "jcjggnnn1\n" +
                "eightdbtfgpfivecnlmnkrpgf1nine\n" +
                "33bngjpkhgfqp4tl97one\n" +
                "6rkmbdjztnfninecdlhnbnf6ninekmvxrqzbl\n" +
                "465\n" +
                "nfklpzppbq65threeeightsix9\n" +
                "2gddbjlcdkx\n" +
                "kclqnmpsixsix4fivepb\n" +
                "stvlnrfdgcslqmveightbmbgmnzlrq8gfjndq6rsv\n" +
                "sjzcfxn7hs\n" +
                "oneeight32nine2ghx2nine\n" +
                "2lhx9\n" +
                "6eightseven9\n" +
                "three9nineone7five\n" +
                "1nrmk\n" +
                "dccbdjqhvfoneeighthjsmfp89hheight9\n" +
                "sixrfjshf9nhzngkgeight\n" +
                "zsixone5fiveeightsix7\n" +
                "vkthreesevenq42982\n" +
                "2h\n" +
                "8five9jkvqtwo9\n" +
                "lkxvfm7qdhvnkt\n" +
                "8jtttvnmxt\n" +
                "1nine91sixsixfour\n" +
                "8threenmffourone\n" +
                "two2zjj39seventhree\n" +
                "c4eighteight7hssvhvlm2six\n" +
                "9eightfivezmnknpl5eight8seven7\n" +
                "threenine4eight14vzmmhczfhxppqs\n" +
                "seven22fivehgtttqthreeseven\n" +
                "5nineeightthree\n" +
                "hfffcgvnkrp5threevccpjmnfn3\n" +
                "19seventwonelj\n" +
                "4nine8\n" +
                "2sixfggckcdt91three6\n" +
                "9fpztvd\n" +
                "pbm384\n" +
                "rqxzzqtlsx8one91tjmqtcmkxhplcmns5three\n" +
                "four13sixgreight64\n" +
                "seven22four\n" +
                "2six946\n" +
                "nine1767three\n" +
                "mdpvkhvbqstqpskhdxgbzt2zsdvsclhlzbcskckz\n" +
                "1775\n" +
                "pgdbfmvffninezhthree6qlrdkbvqthree\n" +
                "29fourtwo\n" +
                "fiveone14bsnrd\n" +
                "loneight1fourpvcgxjsscssftbfxtkq\n" +
                "fhtwobfnmvjxqzbzctxseven8lhxv\n" +
                "ninefive67rqvgnbt\n" +
                "2fivesevenfive4rhpvklfjz9ninezszc\n" +
                "616vvbxfjplsppgpx\n" +
                "rttqfddgone3rcvdljn88jqrlbdmxgv4\n" +
                "8282eightseven\n" +
                "mkhxlkksgsjrczffqmzzsevenv7seven6zv\n" +
                "5hvkqdnpgtzfjbqrtzx5tncqbmxjpqmmzcf9\n" +
                "llpkjvonesixlnf7one8oneseven\n" +
                "five65qzjtwo\n" +
                "xhcjxj1jghxktnmbxml5bbpklmdcthreedzt\n" +
                "h3sevenonevdnjp5zpzfmch\n" +
                "seveneight1mrrkcpbqd\n" +
                "8one5rn\n" +
                "qbffrljhl48qtg1jhngrrbsdhxl6\n" +
                "ndc5sixcxlcgxpbstwoqfffive5\n" +
                "fpfsqrzfjthreehzbcmhss4fivegbtwo8\n" +
                "nine2two\n" +
                "mddbqdmtcjrkqhv2dxfvdg8eight\n" +
                "jbrkj2llgmg36twocvhmxnb\n" +
                "mhdbsnine1\n" +
                "four1mcvjdkmthmhcsz4\n" +
                "59fbsnx7qrtclvrkfoursdpmhdz\n" +
                "6d6four27zeight\n" +
                "1sevenvjbqrd\n" +
                "9fourlmjqn9rd\n" +
                "gfxsrconexrgdzrhzcsh4six\n" +
                "4one5jhsztrspthree\n" +
                "four5eight2\n" +
                "onebtwo4eightfourhkrsgeight\n" +
                "51kjcqqxrjcnnine5\n" +
                "kprdj25twotwovsdhzgmc\n" +
                "htwone4344five1\n" +
                "dvmkvcfcpsqrh1\n" +
                "9twogzkc572sixhktmslseven\n" +
                "fivefive7qnll7seven\n" +
                "svbpx64n31onevzjhhhl\n" +
                "8fbjkdcttwofourtwokj\n" +
                "6twotwo5zkcnxczszfive32\n" +
                "mbfcmsjmg9hmqngl\n" +
                "ninesixsgnfzsmbgrlxbxjstkmmfxc5\n" +
                "two8fourthree9sdxzvpgseventwonez\n" +
                "td3two\n" +
                "onespktrhrktzrcvdgqvdxgbgctdhjmm7shqcbzvfxhzlt\n" +
                "5zfpfksszthtzxznxgkrpc\n" +
                "8xvmsseven592ssmzjdmz\n" +
                "64fkcmhmqdxnseven\n" +
                "vdhkbktf1seven5\n" +
                "tzfvfour3three\n" +
                "fourl7four\n" +
                "dkbbtpd5qbqgb\n" +
                "qzdlttqfhn8chxxbnplt4\n" +
                "qmd78hqdqxtx2rrdvkvvfourtwo\n" +
                "91mmlbnbs5peightmznzhskfjv\n" +
                "2rftqscv\n" +
                "4oneonenineddktjvjlhone\n" +
                "ninetwo5four\n" +
                "1f36xndmtmmbpx1qzqmdkpbp3\n" +
                "hxsevenjg6fiveeightwodps\n" +
                "4mrndsix18\n" +
                "r6klzqlz\n" +
                "ndbrrsvp9\n" +
                "sixsnkh1gvcnine5\n" +
                "bsstxkninethree5ktwo7five\n" +
                "fiveeight9five7\n" +
                "3nine5sixkqlfrpdpcfive3\n" +
                "lrrqkznlrcmbvdr6\n" +
                "8xklphsevenonetworjgpjlrllgqcrxhlskfhpq\n" +
                "fourmsthcgcxjsixcvnvninebdhttzm85\n" +
                "8gnqnhptgkfivesix\n" +
                "8onenine\n" +
                "fivesixone3kpzvnbrjf\n" +
                "9four54\n" +
                "6twothreefthreefivetx\n" +
                "4nxqzkkbgvthree7qxdhtpjv\n" +
                "six5three2ninesevenfive\n" +
                "3cqkmxnbkkh6tnszgzxqk\n" +
                "82tzncrpvjts7\n" +
                "39one5fivenine\n" +
                "51jrdstpqnjdfbbtjz9three6\n" +
                "nqrmg8\n" +
                "7threesix\n" +
                "one6fsxsflbnfivesixthree5\n" +
                "bxbonethree55one\n" +
                "7onextpttrflql6snmbdtbnvvfive\n" +
                "threeklkjkvqzone2vhzsqdg\n" +
                "eight231eightsix5\n" +
                "cflpngxndfivefiveeight4rjrsfrmmtwonen\n" +
                "three8sdone\n" +
                "nine4nine\n" +
                "two2dxzjxkbb2knvg\n" +
                "bplttc53\n" +
                "69hqtkfivesixtwopffgltlsj1rhhslz\n" +
                "6fbg1scccrkjjsnnhpqmphksevendt5pcdl\n" +
                "9onesixsevenfmmxtkdzone\n" +
                "1onetwocrhcqhrxt7sevenr\n" +
                "sixeightxjjqndfqtwo35\n" +
                "9cqvtmfsqrfqhhbkjgbdk\n" +
                "foursixfrtkpcbxgxx5one\n" +
                "429three\n" +
                "84mxhzmbdk8\n" +
                "nine79\n" +
                "xgntrzninemhxtqnine4ltvx\n" +
                "four3seven6qhrzznzctwofour\n" +
                "5h\n" +
                "16eightninejmddlknrxfone\n" +
                "3gjpbjdone\n" +
                "654twocbczrzjnhkgdpqdd\n" +
                "2xkptbxsixnprkhfslj\n" +
                "19mlqcgbfpdonegdvzghjjb\n" +
                "dnslxvmdlpmlsggq1one18\n" +
                "lbxnz487vjlhhsxvcl\n" +
                "sevengvgkk8mfbplfshlhqnrvbtwofour\n" +
                "djfptvqgmkqgnzdvstwomzpcxfthvzpfsglc7\n" +
                "1nlsztzzcbmqseven4fourdqq2\n" +
                "cqcvkcthreeflhbcsbddg8\n" +
                "sevensvtbtdkfkxzbfqznlh1\n" +
                "sevenksn54\n" +
                "4dzv6\n" +
                "lsixninesevenrxn2seven2\n" +
                "bsix2hqsvvvxvkpbg\n" +
                "hplfzmghmbddz2htfkcfblqcdzfrvqpssbxdone\n" +
                "19sqgxkn8four\n" +
                "64ksmvcseven1748\n" +
                "oneoneonedlmsdc1mjn\n" +
                "7218\n" +
                "3xdskntkmlcldqjgxbgx38rkbddntz13\n" +
                "tnqnvshmhrkxbjvxcvdhmx1\n" +
                "twocrzgfourbvtkcthdkrqpbsevenkfv8zczzszpf\n" +
                "fdkdqfgbgnttlpnjrvnine6dvpdhtchfourbv\n" +
                "qqrznptxjseven9twofourtwo\n" +
                "hpdrqkonetvgfour5onepdk\n" +
                "6eightsixninetclcsllxknspxfgxmlxqddvone\n" +
                "twosixmcbbjthreekclp3\n" +
                "kklgzxnk2eight\n" +
                "zgmnine8oneseven\n" +
                "gmcgzggsixvjzzgrs3gbzmxninezrlcfsphzhseven\n" +
                "7sevensix5fivefourh\n" +
                "rh1qzxvcmqjmtspknine\n" +
                "12threecjltwozchdsfnkmchhgv\n" +
                "vktfhngfb391ghtnrqfourfiveone\n" +
                "9eight46xdxkqtkflqdv59four\n" +
                "839sonesix2btrctxfm\n" +
                "hzpjkvqdfg6three2twocsq8tskmdnvdl\n" +
                "5f\n" +
                "dgmvxqbpbjpbronefivehlf8ls9four\n" +
                "sixm7m8three\n" +
                "vgppvrgdlb26623csvkhsd1\n" +
                "2hjfccgbjnhl8176xkpftwo\n" +
                "seven12vgdnrvmmp1\n" +
                "oneoneone7eighttworvpvsjzl\n" +
                "738one99six\n" +
                "sixrjm3\n" +
                "15six44qndpslhnine8twonehkb\n" +
                "912\n" +
                "3blcn\n" +
                "eight81fivexsbkzcthree\n" +
                "kdqlzbnbnkh2mrpz82six3six\n" +
                "sckfhxxjxfivejgtlmdhc3threeoneightrc\n" +
                "znjgdjd8six6onesevenfour4qpnmvtdnnf\n" +
                "7gnbonesixninehreightlmjone\n" +
                "six3fhhlfgmdlgvhvqctcrxxh\n" +
                "982vbjgptnc\n" +
                "sgfnlppbvfzrmntwo9ggqzsixsixxgqvjvffour\n" +
                "ninenine8\n" +
                "kzfmgls5seveneight2\n" +
                "8ninefourzrgjgrqkxrmjlzqb5\n" +
                "eight7five\n" +
                "fbjt4eight7rnhvfkl5knpvjhqdhvmvczxbvrx\n" +
                "35five\n" +
                "7gzjqslr13qsqxltsninetwoxmhgzhl\n" +
                "threefour2three\n" +
                "onethree45\n" +
                "zvt8nvxctwo6\n" +
                "sevenkfournine1drrmrmljsclgbgsd\n" +
                "jfcnrxjjnbsrlblzpvxc84seven3six\n" +
                "sevenonemt7eightseven6\n" +
                "sevenrddndpj85fzzn4zhvthzp\n" +
                "78zfdbmrfgeightgjtqnx\n" +
                "ninerdqndgffive2dlsblldpfthree9\n" +
                "lvzlfqzsixeightkqbnlv5njjsc4plh\n" +
                "jsqhmbt1xvmkgfbghzdplkxdmgvcrkbngrjlpfj\n" +
                "lfnvhdxcx7twoq\n" +
                "five85\n" +
                "1two3two22bdpbskrlph\n" +
                "ninefc31fnhsnhf5\n" +
                "2cxnrgtlvfvmvvmnfjllshmdvvfc48sevennjfk\n" +
                "xbglffkvrzsmz1\n" +
                "czlrrchbkhmz5qkdbtcjlffd5\n" +
                "eight65sn4\n" +
                "7seven2four99mlpskrgoneighthm\n" +
                "9kfpfgzdjdgxjkltdkbkeightmxteightthree\n" +
                "9bdsbeightjvkrmhdkghfive73four3\n" +
                "xeightwoninehcrsdbnvtwovtbkhtxktjslsix3\n" +
                "15fourlgrsk\n" +
                "5xjqd9\n" +
                "four8ttpzxpnrqnkz1\n" +
                "fourvbfhg1rbrngbgfj6nineldqfxvrx\n" +
                "sdpnkkfive9twodz23\n" +
                "sixone4twoktcx\n" +
                "8rjgbnxsixfivebsnthree2fivenmjxx\n" +
                "fourddtxngtd4jvlttthhmz\n" +
                "2nine95four1six9nine\n" +
                "2gmxtrrkftjfnknknineqjqnscctfourzrqdrgs\n" +
                "flghzhfgmn9tckbpmkgsix9\n" +
                "jg9svtdrmlzm31rsrqvc4mggcj\n" +
                "eightdpvfplptwofdgrkstvh8qseven87\n" +
                "eightfour2fourvzksqhxmlkpkfktmdzpmthreetwonehv\n" +
                "nine86kzqvkjqtjfourmpcggd8\n" +
                "8nstjmtmstcnffnksqh\n" +
                "bvgcmbcrgqfourpvs5xs\n" +
                "8three12\n" +
                "5398db9sixvnvcrztrqz\n" +
                "7one62fourlndnshczz522\n" +
                "qxrhp5eight183tfour\n" +
                "fhpzgkt81two57\n" +
                "ktlfdnbone6\n" +
                "stsninecqxpfmdhk41vlpq\n" +
                "eighttqcc5fqnfour84\n" +
                "25gmh12threeltfnfdrxhh5\n" +
                "57four\n" +
                "mqgdhfour67\n" +
                "37ninetxkddhfive\n" +
                "rzrsskzrlzjbcgthreeghbqhdpxfvgjfqclcf4\n" +
                "fourvone2vbpltlrj\n" +
                "xz5four3nineseven\n" +
                "1szrhcmzkftwo9eight2ltjmgjzcblzone\n" +
                "zlnkddtgsb1sixsxvjxgxp2\n" +
                "26sixpzpsixtwozqff\n" +
                "seven99fzqxfmttfgxm\n" +
                "9twonineonefourpttbgkxt8two\n" +
                "fv9\n" +
                "5qcmjsfk6zxjld1\n" +
                "fkjstnvmchsr9q699\n" +
                "nine78three\n" +
                "4rcs6bhbbgzhsstwomnineksbxfzj8\n" +
                "4fmblhqninefive6qbkm\n" +
                "zsgjbfrjfour1sp3\n" +
                "zbfeightfive1oneonernfd\n" +
                "5bxtfvzczbhtzfourqglqdxsc\n" +
                "f9five7five8ddvseven\n" +
                "23bszpdxfjmzg\n" +
                "fivegctmd3vlcgfgnine\n" +
                "63hbdkxljlq\n" +
                "64eight6eight6gxdpmtnbfone\n" +
                "28xcbtt1\n" +
                "1six5\n" +
                "four289";
//        String[] lines = "as1ds1as2dnines".split("\n");
//        String[] lines = secondLong.split("\n");
        String[] lines = secondLong.split("\n");
//        String[] lines = "eightwothree".split("\n");
        int sum = 0;
        for (String line : lines) {
            int number = getNumberCharacters(line.toCharArray());
            int numberReversed = getNumberCharacters(new StringBuilder(line).reverse().toString().toCharArray());

            int value = 10 * number + numberReversed;
            System.out.println(line + " = " + value);
            sum += value;
        }
        System.out.println(sum);

    }

    static NumberMatcher matcher = NumberMatcher.getInstance();

    private static int getNumberCharacters(char[] chars) {
        for (char value : chars) {
            if (isNumber(value)) {
                matcher.walk('q');
                return value - '0';
            }
            int current = matcher.walk(value);
            if (current != -1) {
                matcher.walk('q');
                return current;
            }
        }
        matcher.walk('q');
        return -1;
    }

    private static int getNumber(char[] chars) {
        int firstIdx = -1;
        for (int idx = 0; idx < chars.length; idx++) {
            char current = chars[idx];
            if (isNumber(current)) {
                firstIdx = idx;
                break;
            }
        }

        int secondIdx = -1;
        for (int idx = chars.length - 1; idx >= 0; idx--) {
            char current = chars[idx];
            if (isNumber(current)) {
                secondIdx = idx;
                break;
            }
        }
        if (firstIdx == -1) {
            return 0;
        } else if (firstIdx == secondIdx) {
            return (chars[firstIdx] - '0') * 10 + (chars[firstIdx] - '0');
        } else {
            return (chars[firstIdx] - '0') * 10 + (chars[secondIdx] - '0');
        }
    }

    private static boolean isNumber(char current) {
        return current >= '0' && current <= '9';
    }
}
